--- 
- 
  hosts: localhost
  tasks: 
    - 
      command: "dcos marathon app add shipconsole.json"
      name: "Deploy Mesos Application"
      register: docker
    - 
      command: "ant dist"
    - 
      command: "docker build --no-cache --tag bharadwajsnp/ansibledemo:latest ."
    - 
      command: "docker login -u bharadwajsnp -p Webhosting123"
    - 
      command: "docker push bharadwajsnp/ansibledemo:latest"
    - 
      debug: var=docker.stdout
