// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.stampsws.proxy;


public class ArrayOfStoreShippingMethodOption implements java.io.Serializable {
    private com.aasc.erp.carrier.stampsws.proxy.StoreShippingMethodOption[] storeShippingMethodOption;
    
    public ArrayOfStoreShippingMethodOption() {
    }
    
    public ArrayOfStoreShippingMethodOption(com.aasc.erp.carrier.stampsws.proxy.StoreShippingMethodOption[] sourceArray) {
        storeShippingMethodOption = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.stampsws.proxy.StoreShippingMethodOption[] sourceArray) {
        this.storeShippingMethodOption = sourceArray;
    }
    
    public com.aasc.erp.carrier.stampsws.proxy.StoreShippingMethodOption[] toArray() {
        return storeShippingMethodOption;
    }
    
    public com.aasc.erp.carrier.stampsws.proxy.StoreShippingMethodOption[] getStoreShippingMethodOption() {
        return storeShippingMethodOption;
    }
    
    public void setStoreShippingMethodOption(com.aasc.erp.carrier.stampsws.proxy.StoreShippingMethodOption[] storeShippingMethodOption) {
        this.storeShippingMethodOption = storeShippingMethodOption;
    }
}
