// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.stampsws.proxy;


public class CapabilitiesV5 extends com.aasc.erp.carrier.stampsws.proxy.CapabilitiesV4 implements java.io.Serializable {
    protected boolean canCreateCriticalMail;
    
    public CapabilitiesV5() {
    }
    
    public boolean isCanCreateCriticalMail() {
        return canCreateCriticalMail;
    }
    
    public void setCanCreateCriticalMail(boolean canCreateCriticalMail) {
        this.canCreateCriticalMail = canCreateCriticalMail;
    }
}
