// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.stampsws.proxy;


public class CodewordType implements java.io.Serializable {
    private java.lang.String value;
    private static final String _MothersMaidenNameString = "MothersMaidenName";
    private static final String _PetsNameString = "PetsName";
    private static final String _BirthCityString = "BirthCity";
    private static final String _Last4SocialSecurityNumberString = "Last4SocialSecurityNumber";
    private static final String _Last4DriversLicenseString = "Last4DriversLicense";
    
    public static final java.lang.String _MothersMaidenName = new java.lang.String(_MothersMaidenNameString);
    public static final java.lang.String _PetsName = new java.lang.String(_PetsNameString);
    public static final java.lang.String _BirthCity = new java.lang.String(_BirthCityString);
    public static final java.lang.String _Last4SocialSecurityNumber = new java.lang.String(_Last4SocialSecurityNumberString);
    public static final java.lang.String _Last4DriversLicense = new java.lang.String(_Last4DriversLicenseString);
    
    public static final CodewordType MothersMaidenName = new CodewordType(_MothersMaidenName);
    public static final CodewordType PetsName = new CodewordType(_PetsName);
    public static final CodewordType BirthCity = new CodewordType(_BirthCity);
    public static final CodewordType Last4SocialSecurityNumber = new CodewordType(_Last4SocialSecurityNumber);
    public static final CodewordType Last4DriversLicense = new CodewordType(_Last4DriversLicense);
    
    protected CodewordType(java.lang.String value) {
        this.value = value;
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static CodewordType fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (MothersMaidenName.value.equals(value)) {
            return MothersMaidenName;
        }if (PetsName.value.equals(value)) {
            return PetsName;
        }if (BirthCity.value.equals(value)) {
            return BirthCity;
        }if (Last4SocialSecurityNumber.value.equals(value)) {
            return Last4SocialSecurityNumber;
        }if (Last4DriversLicense.value.equals(value)) {
            return Last4DriversLicense;
        }
        throw new IllegalArgumentException();
    }
    
    public static CodewordType fromString(String value)
        throws java.lang.IllegalStateException {
        if (value.equals(_MothersMaidenNameString)) {
            return MothersMaidenName;
        }if (value.equals(_PetsNameString)) {
            return PetsName;
        }if (value.equals(_BirthCityString)) {
            return BirthCity;
        }if (value.equals(_Last4SocialSecurityNumberString)) {
            return Last4SocialSecurityNumber;
        }if (value.equals(_Last4DriversLicenseString)) {
            return Last4DriversLicense;
        }
        throw new IllegalArgumentException();
    }
    
    public String toString() {
        return value.toString();
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof CodewordType)) {
            return false;
        }
        return ((CodewordType)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
