// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.stampsws.proxy;


public class Credentials implements java.io.Serializable {
    protected java.lang.String integrationID;
    protected java.lang.String username;
    protected java.lang.String password;
    
    public Credentials() {
    }
    
    public java.lang.String getIntegrationID() {
        return integrationID;
    }
    
    public void setIntegrationID(java.lang.String integrationID) {
        this.integrationID = integrationID;
    }
    
    public java.lang.String getUsername() {
        return username;
    }
    
    public void setUsername(java.lang.String username) {
        this.username = username;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
}
