// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.stampsws.proxy;


public class ImageType implements java.io.Serializable {
    private java.lang.String value;
    private static final String _AutoString = "Auto";
    private static final String _PngString = "Png";
    private static final String _GifString = "Gif";
    private static final String _PdfString = "Pdf";
    private static final String _EplString = "Epl";
    private static final String _JpgString = "Jpg";
    private static final String _PrintOncePdfString = "PrintOncePdf";
    private static final String _EncryptedPngUrlString = "EncryptedPngUrl";
    private static final String _ZplString = "Zpl";
    private static final String _AZplString = "AZpl";
    private static final String _BZplString = "BZpl";
    
    public static final java.lang.String _Auto = new java.lang.String(_AutoString);
    public static final java.lang.String _Png = new java.lang.String(_PngString);
    public static final java.lang.String _Gif = new java.lang.String(_GifString);
    public static final java.lang.String _Pdf = new java.lang.String(_PdfString);
    public static final java.lang.String _Epl = new java.lang.String(_EplString);
    public static final java.lang.String _Jpg = new java.lang.String(_JpgString);
    public static final java.lang.String _PrintOncePdf = new java.lang.String(_PrintOncePdfString);
    public static final java.lang.String _EncryptedPngUrl = new java.lang.String(_EncryptedPngUrlString);
    public static final java.lang.String _Zpl = new java.lang.String(_ZplString);
    public static final java.lang.String _AZpl = new java.lang.String(_AZplString);
    public static final java.lang.String _BZpl = new java.lang.String(_BZplString);
    
    public static final ImageType Auto = new ImageType(_Auto);
    public static final ImageType Png = new ImageType(_Png);
    public static final ImageType Gif = new ImageType(_Gif);
    public static final ImageType Pdf = new ImageType(_Pdf);
    public static final ImageType Epl = new ImageType(_Epl);
    public static final ImageType Jpg = new ImageType(_Jpg);
    public static final ImageType PrintOncePdf = new ImageType(_PrintOncePdf);
    public static final ImageType EncryptedPngUrl = new ImageType(_EncryptedPngUrl);
    public static final ImageType Zpl = new ImageType(_Zpl);
    public static final ImageType AZpl = new ImageType(_AZpl);
    public static final ImageType BZpl = new ImageType(_BZpl);
    
    public ImageType(java.lang.String value) {
        this.value = value;
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static ImageType fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (Auto.value.equals(value)) {
            return Auto;
        }if (Png.value.equals(value)) {
            return Png;
        }if (Gif.value.equals(value)) {
            return Gif;
        }if (Pdf.value.equals(value)) {
            return Pdf;
        }if (Epl.value.equals(value)) {
            return Epl;
        }if (Jpg.value.equals(value)) {
            return Jpg;
        }if (PrintOncePdf.value.equals(value)) {
            return PrintOncePdf;
        }if (EncryptedPngUrl.value.equals(value)) {
            return EncryptedPngUrl;
        }if (Zpl.value.equals(value)) {
            return Zpl;
        }if (AZpl.value.equals(value)) {
            return AZpl;
        }if (BZpl.value.equals(value)) {
            return BZpl;
        }
        throw new IllegalArgumentException();
    }
    
    public static ImageType fromString(String value)
        throws java.lang.IllegalStateException {
        if (value.equals(_AutoString)) {
            return Auto;
        }if (value.equals(_PngString)) {
            return Png;
        }if (value.equals(_GifString)) {
            return Gif;
        }if (value.equals(_PdfString)) {
            return Pdf;
        }if (value.equals(_EplString)) {
            return Epl;
        }if (value.equals(_JpgString)) {
            return Jpg;
        }if (value.equals(_PrintOncePdfString)) {
            return PrintOncePdf;
        }if (value.equals(_EncryptedPngUrlString)) {
            return EncryptedPngUrl;
        }if (value.equals(_ZplString)) {
            return Zpl;
        }if (value.equals(_AZplString)) {
            return AZpl;
        }if (value.equals(_BZplString)) {
            return BZpl;
        }
        throw new IllegalArgumentException();
    }
    
    public String toString() {
        return value.toString();
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof ImageType)) {
            return false;
        }
        return ((ImageType)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
