// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.stampsws.proxy;


public class RegisterAccountResponse implements java.io.Serializable {
    protected com.aasc.erp.carrier.stampsws.proxy.RegistrationStatus registrationStatus;
    protected java.lang.String suggestedUserName;
    protected int userId;
    protected java.lang.String promoUrl;
    
    public RegisterAccountResponse() {
    }
    
    public com.aasc.erp.carrier.stampsws.proxy.RegistrationStatus getRegistrationStatus() {
        return registrationStatus;
    }
    
    public void setRegistrationStatus(com.aasc.erp.carrier.stampsws.proxy.RegistrationStatus registrationStatus) {
        this.registrationStatus = registrationStatus;
    }
    
    public java.lang.String getSuggestedUserName() {
        return suggestedUserName;
    }
    
    public void setSuggestedUserName(java.lang.String suggestedUserName) {
        this.suggestedUserName = suggestedUserName;
    }
    
    public int getUserId() {
        return userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    public java.lang.String getPromoUrl() {
        return promoUrl;
    }
    
    public void setPromoUrl(java.lang.String promoUrl) {
        this.promoUrl = promoUrl;
    }
}
