// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.stampsws.proxy;


public class ResidentialDeliveryIndicatorType implements java.io.Serializable {
    private java.lang.String value;
    private static final String _YesString = "Yes";
    private static final String _NoString = "No";
    private static final String _UnknownString = "Unknown";
    private static final String _UnsupportedString = "Unsupported";
    
    public static final java.lang.String _Yes = new java.lang.String(_YesString);
    public static final java.lang.String _No = new java.lang.String(_NoString);
    public static final java.lang.String _Unknown = new java.lang.String(_UnknownString);
    public static final java.lang.String _Unsupported = new java.lang.String(_UnsupportedString);
    
    public static final ResidentialDeliveryIndicatorType Yes = new ResidentialDeliveryIndicatorType(_Yes);
    public static final ResidentialDeliveryIndicatorType No = new ResidentialDeliveryIndicatorType(_No);
    public static final ResidentialDeliveryIndicatorType Unknown = new ResidentialDeliveryIndicatorType(_Unknown);
    public static final ResidentialDeliveryIndicatorType Unsupported = new ResidentialDeliveryIndicatorType(_Unsupported);
    
    protected ResidentialDeliveryIndicatorType(java.lang.String value) {
        this.value = value;
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static ResidentialDeliveryIndicatorType fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (Yes.value.equals(value)) {
            return Yes;
        }if (No.value.equals(value)) {
            return No;
        }if (Unknown.value.equals(value)) {
            return Unknown;
        }if (Unsupported.value.equals(value)) {
            return Unsupported;
        }
        throw new IllegalArgumentException();
    }
    
    public static ResidentialDeliveryIndicatorType fromString(String value)
        throws java.lang.IllegalStateException {
        if (value.equals(_YesString)) {
            return Yes;
        }if (value.equals(_NoString)) {
            return No;
        }if (value.equals(_UnknownString)) {
            return Unknown;
        }if (value.equals(_UnsupportedString)) {
            return Unsupported;
        }
        throw new IllegalArgumentException();
    }
    
    public String toString() {
        return value.toString();
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof ResidentialDeliveryIndicatorType)) {
            return false;
        }
        return ((ResidentialDeliveryIndicatorType)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
