// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.stampsws.proxy;

public interface SwsimV37Soap extends java.rmi.Remote {
    /**
    Generate a SCAN form.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.CreateScanFormResponse createScanForm(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, java.lang.String[] stampsTxIDs, com.aasc.erp.carrier.stampsws.proxy.Address fromAddress, com.aasc.erp.carrier.stampsws.proxy.ImageType imageType, boolean printInstructions, java.util.Calendar shipDate) throws 
         java.rmi.RemoteException;
    /**
    Generate an indicium.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.CreateIndiciumResponse createIndicium(java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String integratorTxID, java.lang.String trackingNumber, com.aasc.erp.carrier.stampsws.proxy.RateV14 rate, com.aasc.erp.carrier.stampsws.proxy.Address from, com.aasc.erp.carrier.stampsws.proxy.Address to, java.lang.String customerID, com.aasc.erp.carrier.stampsws.proxy.CustomsV2 customs, java.lang.Boolean sampleOnly, com.aasc.erp.carrier.stampsws.proxy.ImageType imageType, com.aasc.erp.carrier.stampsws.proxy.EltronPrinterDPIType eltronPrinterDPIType, java.lang.String memo, java.lang.Integer cost_code_id, java.lang.Boolean deliveryNotification, com.aasc.erp.carrier.stampsws.proxy.ShipmentNotification shipmentNotification, java.lang.Integer rotationDegrees, java.lang.Integer horizontalOffset, java.lang.Integer verticalOffset, java.lang.Integer printDensity, java.lang.Boolean printMemo, java.lang.Boolean printInstructions, java.lang.Boolean requestPostageHash, com.aasc.erp.carrier.stampsws.proxy.NonDeliveryOption nonDeliveryOption, com.aasc.erp.carrier.stampsws.proxy.Address redirectTo, java.lang.String originalPostageHash, java.lang.Boolean returnImageData, java.lang.String internalTransactionNumber, com.aasc.erp.carrier.stampsws.proxy.PaperSizeV1 paperSize, com.aasc.erp.carrier.stampsws.proxy.LabelRecipientInfo emailLabelTo) throws 
         java.rmi.RemoteException;
    /**
    Generate an unfunded indicium.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.CreateUnfundedIndiciumResponse createUnfundedIndicium(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, java.lang.String integratorTxID, java.lang.String trackingNumber, com.aasc.erp.carrier.stampsws.proxy.RateV14 rate, com.aasc.erp.carrier.stampsws.proxy.Address from, com.aasc.erp.carrier.stampsws.proxy.Address to, java.lang.String customerID, com.aasc.erp.carrier.stampsws.proxy.CustomsV2 customs, java.lang.Boolean sampleOnly, com.aasc.erp.carrier.stampsws.proxy.ImageType imageType, com.aasc.erp.carrier.stampsws.proxy.EltronPrinterDPIType eltronPrinterDPIType, java.lang.String memo, java.lang.Integer cost_code_id, java.lang.String recipient_email, java.lang.Boolean deliveryNotification, java.lang.Boolean shipmentNotificationCC, java.lang.Boolean shipmentNotificationCCToMain, java.lang.Boolean shipmentNotificationFromCompany, java.lang.Boolean shipmentNotificationCompanyInSubject, java.lang.Integer rotationDegrees) throws 
         java.rmi.RemoteException;
    /**
    Generate an envelope indicium.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.CreateEnvelopeIndiciumResponse createEnvelopeIndicium(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, java.lang.String integratorTxID, com.aasc.erp.carrier.stampsws.proxy.RateV14 rate, com.aasc.erp.carrier.stampsws.proxy.Address from, com.aasc.erp.carrier.stampsws.proxy.Address to, java.lang.String customerID, com.aasc.erp.carrier.stampsws.proxy.CreateIndiciumModeV1 mode, com.aasc.erp.carrier.stampsws.proxy.ImageType imageType, java.lang.Integer costCodeId, java.lang.Boolean hideFIM) throws 
         java.rmi.RemoteException;
    /**
    Generate NetStamps indicia.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.CreateNetStampsIndiciaResponse createNetStampsIndicia(java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String integratorTxId, java.lang.String layout, com.aasc.erp.carrier.stampsws.proxy.NetStampV10[] netStamps, com.aasc.erp.carrier.stampsws.proxy.Address from, java.lang.Boolean sampleOnly, com.aasc.erp.carrier.stampsws.proxy.ImageType imageType, java.lang.Integer cost_code_id, java.lang.Integer imageId, java.lang.Boolean returnIndiciaData) throws 
         java.rmi.RemoteException;
    /**
    Generate a mailing label sheet.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.CreateMailingLabelIndiciaResponse createMailingLabelIndicia(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, java.lang.String integratorTxId, java.lang.String layout, java.lang.Boolean printAddress, java.lang.Integer startRow, java.lang.Integer startColumn, com.aasc.erp.carrier.stampsws.proxy.IndiciumInfoV6[] indiciumInfo, com.aasc.erp.carrier.stampsws.proxy.CreateIndiciumModeV1 mode, com.aasc.erp.carrier.stampsws.proxy.ImageType imageType) throws 
         java.rmi.RemoteException;
    /**
    Calculate a rate or a list of rates.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.GetRatesResponse getRates(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.RateV14 rate) throws 
         java.rmi.RemoteException;
    /**
    Change Plan.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.ChangePlanResponse changePlan(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, java.lang.Integer planId, java.lang.String promoCode) throws 
         java.rmi.RemoteException;
    /**
    Get URL for a Stamps.com web page.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.GetURLResponse getURL(java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, com.aasc.erp.carrier.stampsws.proxy.UrlType URLType, java.lang.String applicationContext) throws 
         java.rmi.RemoteException;
    /**
    Recover Username.

    **/
    public void recoverUsername(java.lang.String emailAddress) throws 
         java.rmi.RemoteException;
    /**
    Get list of supported countries.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.GetSupportedCountriesResponse getSupportedCountries(java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Credentials credentials) throws 
         java.rmi.RemoteException;
    /**
    Change Password.

    **/
    public java.lang.String changePassword(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, java.lang.String oldPassword, java.lang.String newPassword) throws 
         java.rmi.RemoteException;
    /**
    Price Store Orders.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.PriceOrderResponse priceOrder(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Sku[] skus, java.lang.String promoCode, com.aasc.erp.carrier.stampsws.proxy.Address shippingAddress) throws 
         java.rmi.RemoteException;
    /**
    Place Store Orders.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.PlaceOrderResponse placeOrder(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Sku[] skus, java.lang.String promoCode, com.aasc.erp.carrier.stampsws.proxy.Address shippingAddress, com.aasc.erp.carrier.stampsws.proxy.StoreShippingMethodType storeShippingMethod) throws 
         java.rmi.RemoteException;
    /**
    Cleanse an address.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.CleanseAddressResponse cleanseAddress(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Address address) throws 
         java.rmi.RemoteException;
    /**
    Get NetStamps Images.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.GetNetStampsImagesResponse getNetStampsImages(java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Credentials credentials) throws 
         java.rmi.RemoteException;
    /**
    Get status of plan change.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.GetChangePlanStatusResponse getChangePlanStatus(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, int transactionID) throws 
         java.rmi.RemoteException;
    /**
    Purchase additional postage.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.PurchasePostageResponse purchasePostage(java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.math.BigDecimal purchaseAmount, java.math.BigDecimal controlTotal, com.aasc.erp.carrier.stampsws.proxy.MachineInfo MI, java.lang.String integratorTxID) throws 
         java.rmi.RemoteException;
    /**
    Resubmit Purchase.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.ResubmitPurchaseResponse resubmitPurchase(java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String resubmitCookie) throws 
         java.rmi.RemoteException;
    /**
    Request carrier pickup from USPS.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.CarrierPickupResponse carrierPickup(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, java.lang.String firstName, java.lang.String lastName, java.lang.String company, java.lang.String address, java.lang.String suiteOrApt, java.lang.String city, java.lang.String state, java.lang.String ZIP, java.lang.String ZIP4, java.lang.String phoneNumber, java.lang.String phoneExt, java.lang.Integer numberOfExpressMailPieces, java.lang.Integer numberOfPriorityMailPieces, java.lang.Integer numberOfInternationalPieces, java.lang.Integer numberOfOtherPieces, int totalWeightOfPackagesLbs, com.aasc.erp.carrier.stampsws.proxy.CarrierPickupLocationV1 packageLocation, java.lang.String specialInstruction) throws 
         java.rmi.RemoteException;
    /**
    Get list of NetStamps layouts.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.EnumNetStampsLayoutsResponse enumNetStampsLayouts(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator) throws 
         java.rmi.RemoteException;
    /**
    Get list of cost codes.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.EnumCostCodesResponse enumCostCodes(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator) throws 
         java.rmi.RemoteException;
    /**
    Authenticate with transfer authenticator.

    **/
    public java.lang.String authenticateWithTransferAuthenticator(java.lang.String integrationID, java.lang.String transferAuthenticator) throws 
         java.rmi.RemoteException;
    /**
    Cancel a previously issued indicium.

    **/
    public java.lang.String cancelIndicium(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator, java.lang.String trackingNumber, java.lang.String stampsTxID) throws 
         java.rmi.RemoteException;
    /**
    Start a password reset by sending a temporary password to the e-mail address on file.

    **/
    public void startPasswordReset(java.lang.String username, java.lang.String codeword1, java.lang.String codeword2, java.lang.String integrationId) throws 
         java.rmi.RemoteException;
    /**
    Finish a password reset, setting the permanent password to a new password.

    **/
    public void finishPasswordReset(java.lang.String username, java.lang.String tempPassword, java.lang.String newPassword, java.lang.String integrationId) throws 
         java.rmi.RemoteException;
    /**
    Retrieve codeword questions for user for starting password reset.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.GetCodewordQuestionsResponse getCodewordQuestions(java.lang.String username, java.lang.String integrationId) throws 
         java.rmi.RemoteException;
    /**
    Register a new Stamps.com account.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.RegisterAccountResponse registerAccount(java.lang.String integrationID, java.lang.String userName, java.lang.String password, com.aasc.erp.carrier.stampsws.proxy.CodewordType codeword1Type, java.lang.String codeword1, com.aasc.erp.carrier.stampsws.proxy.CodewordType codeword2Type, java.lang.String codeword2, com.aasc.erp.carrier.stampsws.proxy.Address physicalAddress, com.aasc.erp.carrier.stampsws.proxy.Address mailingAddress, com.aasc.erp.carrier.stampsws.proxy.MachineInfo machineInfo, java.lang.String email, com.aasc.erp.carrier.stampsws.proxy.AccountType accountType, java.lang.String promoCode, com.aasc.erp.carrier.stampsws.proxy.CreditCard creditCard, com.aasc.erp.carrier.stampsws.proxy.AchAccount achAccount) throws 
         java.rmi.RemoteException;
    /**
    Void an unfunded indicium.

    **/
    public java.lang.String voidUnfundedIndicium(java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String stampsTxID) throws 
         java.rmi.RemoteException;
    /**
    Fund an unfunded indicium.

    **/
    public java.lang.String fundUnfundedIndicium(java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String stampsTxID) throws 
         java.rmi.RemoteException;
    /**
    Initial authentication.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.AuthenticateUserResponse authenticateUser(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials) throws 
         java.rmi.RemoteException;
    /**
    Get account information, including postage balance.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.GetAccountInfoResponse getAccountInfo(com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String authenticator) throws 
         java.rmi.RemoteException;
    /**
    Get status of postage purchase.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.GetPurchaseStatusResponse getPurchaseStatus(java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, int transactionID) throws 
         java.rmi.RemoteException;
    /**
    Get tracking events for shipment.

    **/
    public com.aasc.erp.carrier.stampsws.proxy.TrackShipmentResponse trackShipment(java.lang.String authenticator, com.aasc.erp.carrier.stampsws.proxy.Credentials credentials, java.lang.String stampsTxID, java.lang.String trackingNumber) throws 
         java.rmi.RemoteException;
}
