// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy;

public interface IwcfPack extends java.rmi.Remote {
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRateResponseType packRate(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRateRequest packRateRequest, com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] params) throws 
         java.rmi.RemoteException;
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackResponseType pack(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRequest packRequest, com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] params) throws 
         java.rmi.RemoteException;
}
