// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class App_Db_VersionResponse implements java.io.Serializable {
    protected java.lang.String app_Db_VersionResult;
    
    public App_Db_VersionResponse() {
    }
    
    public java.lang.String getApp_Db_VersionResult() {
        return app_Db_VersionResult;
    }
    
    public void setApp_Db_VersionResult(java.lang.String app_Db_VersionResult) {
        this.app_Db_VersionResult = app_Db_VersionResult;
    }
}
