// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfPackRate implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate[] packRate;
    
    public ArrayOfPackRate() {
    }
    
    public ArrayOfPackRate(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate[] sourceArray) {
        packRate = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate[] sourceArray) {
        this.packRate = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate[] toArray() {
        return packRate;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate[] getPackRate() {
        return packRate;
    }
    
    public void setPackRate(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate[] packRate) {
        this.packRate = packRate;
    }
}
