// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfCompoundError implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CompoundError[] compoundError;
    
    public ArrayOfCompoundError() {
    }
    
    public ArrayOfCompoundError(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CompoundError[] sourceArray) {
        compoundError = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CompoundError[] sourceArray) {
        this.compoundError = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CompoundError[] toArray() {
        return compoundError;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CompoundError[] getCompoundError() {
        return compoundError;
    }
    
    public void setCompoundError(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CompoundError[] compoundError) {
        this.compoundError = compoundError;
    }
}
