// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfSoxProperty implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxProperty[] soxProperty;
    
    public ArrayOfSoxProperty() {
    }
    
    public ArrayOfSoxProperty(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxProperty[] sourceArray) {
        soxProperty = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxProperty[] sourceArray) {
        this.soxProperty = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxProperty[] toArray() {
        return soxProperty;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxProperty[] getSoxProperty() {
        return soxProperty;
    }
    
    public void setSoxProperty(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxProperty[] soxProperty) {
        this.soxProperty = soxProperty;
    }
}
