// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfContainer implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Container[] container;
    
    public ArrayOfContainer() {
    }
    
    public ArrayOfContainer(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Container[] sourceArray) {
        container = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Container[] sourceArray) {
        this.container = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Container[] toArray() {
        return container;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Container[] getContainer() {
        return container;
    }
    
    public void setContainer(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Container[] container) {
        this.container = container;
    }
}
