// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfPack implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Pack[] pack;
    
    public ArrayOfPack() {
    }
    
    public ArrayOfPack(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Pack[] sourceArray) {
        pack = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Pack[] sourceArray) {
        this.pack = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Pack[] toArray() {
        return pack;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Pack[] getPack() {
        return pack;
    }
    
    public void setPack(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Pack[] pack) {
        this.pack = pack;
    }
}
