// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfDocumentProfile implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.DocumentProfile[] documentProfile;
    
    public ArrayOfDocumentProfile() {
    }
    
    public ArrayOfDocumentProfile(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.DocumentProfile[] sourceArray) {
        documentProfile = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.DocumentProfile[] sourceArray) {
        this.documentProfile = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.DocumentProfile[] toArray() {
        return documentProfile;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.DocumentProfile[] getDocumentProfile() {
        return documentProfile;
    }
    
    public void setDocumentProfile(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.DocumentProfile[] documentProfile) {
        this.documentProfile = documentProfile;
    }
}
