// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfPrinter implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Printer[] printer;
    
    public ArrayOfPrinter() {
    }
    
    public ArrayOfPrinter(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Printer[] sourceArray) {
        printer = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Printer[] sourceArray) {
        this.printer = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Printer[] toArray() {
        return printer;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Printer[] getPrinter() {
        return printer;
    }
    
    public void setPrinter(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Printer[] printer) {
        this.printer = printer;
    }
}
