// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfInt implements java.io.Serializable {
    private int[] _int;
    
    public ArrayOfInt() {
    }
    
    public ArrayOfInt(int[] sourceArray) {
        _int = sourceArray;
    }
    
    public void fromArray(int[] sourceArray) {
        this._int = sourceArray;
    }
    
    public int[] toArray() {
        return _int;
    }
    
    public int[] get_int() {
        return _int;
    }
    
    public void set_int(int[] _int) {
        this._int = _int;
    }
}
