// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfPackageResponse implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackageResponse[] packageResponse;
    
    public ArrayOfPackageResponse() {
    }
    
    public ArrayOfPackageResponse(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackageResponse[] sourceArray) {
        packageResponse = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackageResponse[] sourceArray) {
        this.packageResponse = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackageResponse[] toArray() {
        return packageResponse;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackageResponse[] getPackageResponse() {
        return packageResponse;
    }
    
    public void setPackageResponse(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackageResponse[] packageResponse) {
        this.packageResponse = packageResponse;
    }
}
