// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfLong implements java.io.Serializable {
    private long[] _long;
    
    public ArrayOfLong() {
    }
    
    public ArrayOfLong(long[] sourceArray) {
        _long = sourceArray;
    }
    
    public void fromArray(long[] sourceArray) {
        this._long = sourceArray;
    }
    
    public long[] toArray() {
        return _long;
    }
    
    public long[] get_long() {
        return _long;
    }
    
    public void set_long(long[] _long) {
        this._long = _long;
    }
}
