// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfCloseOutResult implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CloseOutResult[] closeOutResult;
    
    public ArrayOfCloseOutResult() {
    }
    
    public ArrayOfCloseOutResult(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CloseOutResult[] sourceArray) {
        closeOutResult = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CloseOutResult[] sourceArray) {
        this.closeOutResult = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CloseOutResult[] toArray() {
        return closeOutResult;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CloseOutResult[] getCloseOutResult() {
        return closeOutResult;
    }
    
    public void setCloseOutResult(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CloseOutResult[] closeOutResult) {
        this.closeOutResult = closeOutResult;
    }
}
