// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfGroup implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Group[] group;
    
    public ArrayOfGroup() {
    }
    
    public ArrayOfGroup(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Group[] sourceArray) {
        group = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Group[] sourceArray) {
        this.group = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Group[] toArray() {
        return group;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Group[] getGroup() {
        return group;
    }
    
    public void setGroup(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Group[] group) {
        this.group = group;
    }
}
