// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfGrouping implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Grouping[] grouping;
    
    public ArrayOfGrouping() {
    }
    
    public ArrayOfGrouping(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Grouping[] sourceArray) {
        grouping = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Grouping[] sourceArray) {
        this.grouping = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Grouping[] toArray() {
        return grouping;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Grouping[] getGrouping() {
        return grouping;
    }
    
    public void setGrouping(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Grouping[] grouping) {
        this.grouping = grouping;
    }
}
