// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfPackOrderLine implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackOrderLine[] packOrderLine;
    
    public ArrayOfPackOrderLine() {
    }
    
    public ArrayOfPackOrderLine(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackOrderLine[] sourceArray) {
        packOrderLine = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackOrderLine[] sourceArray) {
        this.packOrderLine = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackOrderLine[] toArray() {
        return packOrderLine;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackOrderLine[] getPackOrderLine() {
        return packOrderLine;
    }
    
    public void setPackOrderLine(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackOrderLine[] packOrderLine) {
        this.packOrderLine = packOrderLine;
    }
}
