// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ArrayOfSoxCountry implements java.io.Serializable {
    private com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxCountry[] soxCountry;
    
    public ArrayOfSoxCountry() {
    }
    
    public ArrayOfSoxCountry(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxCountry[] sourceArray) {
        soxCountry = sourceArray;
    }
    
    public void fromArray(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxCountry[] sourceArray) {
        this.soxCountry = sourceArray;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxCountry[] toArray() {
        return soxCountry;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxCountry[] getSoxCountry() {
        return soxCountry;
    }
    
    public void setSoxCountry(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxCountry[] soxCountry) {
        this.soxCountry = soxCountry;
    }
}
