// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class ChangeShipperSymbol implements java.io.Serializable {
    protected java.lang.String currentShipper;
    protected java.lang.String newShipper;
    
    public ChangeShipperSymbol() {
    }
    
    public java.lang.String getCurrentShipper() {
        return currentShipper;
    }
    
    public void setCurrentShipper(java.lang.String currentShipper) {
        this.currentShipper = currentShipper;
    }
    
    public java.lang.String getNewShipper() {
        return newShipper;
    }
    
    public void setNewShipper(java.lang.String newShipper) {
        this.newShipper = newShipper;
    }
}
