// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class CommodityContent implements java.io.Serializable {
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_1;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_2;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_3;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_4;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_5;
    protected java.lang.Integer cert_of_origin_method;
    protected java.lang.Integer commodity_condition;
    protected java.lang.Boolean ddtc_eligible_party;
    protected java.lang.Long ddtc_quantity;
    protected java.lang.String ddtc_registration_number;
    protected java.lang.Boolean ddtc_sme;
    protected java.lang.String ddtc_unit_measure;
    protected java.lang.String ddtc_usml_category_code;
    protected java.lang.String description;
    protected java.lang.String eccn;
    protected java.lang.String export_harmonized_code;
    protected java.lang.String export_information_code;
    protected java.math.BigDecimal export_quantity_1;
    protected java.math.BigDecimal export_quantity_2;
    protected java.lang.String export_quantity_unit_measure_1;
    protected java.lang.String export_quantity_unit_measure_2;
    protected java.lang.String harmonized_code;
    protected java.lang.String license_expiration_date;
    protected java.lang.String license_number;
    protected java.lang.String license_type;
    protected java.math.BigDecimal license_unit_value;
    protected java.lang.String license_unit_value_unit;
    protected java.lang.String manufacturer_id;
    protected java.lang.Integer nafta_preference_criterion;
    protected java.lang.Integer nafta_producer;
    protected java.lang.String nafta_rvc_avg_end_date;
    protected java.lang.String nafta_rvc_avg_start_date;
    protected java.lang.Integer nafta_rvc_method;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.NameAddress origin;
    protected java.lang.String origin_country;
    protected java.lang.String origin_description;
    protected java.lang.String origin_tax_id;
    protected java.lang.String product_code;
    protected java.lang.Long quantity;
    protected java.lang.String quantity_unit_measure;
    protected java.lang.Integer restricted_article_type;
    protected java.lang.Integer sed_method;
    protected java.math.BigDecimal unit_value;
    protected java.lang.String unit_value_unit;
    protected java.math.BigDecimal unit_weight;
    protected java.lang.String unit_weight_unit;
    
    public CommodityContent() {
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] getUser_data_1() {
        return user_data_1;
    }
    
    public void setUser_data_1(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_1) {
        this.user_data_1 = user_data_1;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] getUser_data_2() {
        return user_data_2;
    }
    
    public void setUser_data_2(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_2) {
        this.user_data_2 = user_data_2;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] getUser_data_3() {
        return user_data_3;
    }
    
    public void setUser_data_3(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_3) {
        this.user_data_3 = user_data_3;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] getUser_data_4() {
        return user_data_4;
    }
    
    public void setUser_data_4(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_4) {
        this.user_data_4 = user_data_4;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] getUser_data_5() {
        return user_data_5;
    }
    
    public void setUser_data_5(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_5) {
        this.user_data_5 = user_data_5;
    }
    
    public java.lang.Integer getCert_of_origin_method() {
        return cert_of_origin_method;
    }
    
    public void setCert_of_origin_method(java.lang.Integer cert_of_origin_method) {
        this.cert_of_origin_method = cert_of_origin_method;
    }
    
    public java.lang.Integer getCommodity_condition() {
        return commodity_condition;
    }
    
    public void setCommodity_condition(java.lang.Integer commodity_condition) {
        this.commodity_condition = commodity_condition;
    }
    
    public java.lang.Boolean getDdtc_eligible_party() {
        return ddtc_eligible_party;
    }
    
    public void setDdtc_eligible_party(java.lang.Boolean ddtc_eligible_party) {
        this.ddtc_eligible_party = ddtc_eligible_party;
    }
    
    public java.lang.Long getDdtc_quantity() {
        return ddtc_quantity;
    }
    
    public void setDdtc_quantity(java.lang.Long ddtc_quantity) {
        this.ddtc_quantity = ddtc_quantity;
    }
    
    public java.lang.String getDdtc_registration_number() {
        return ddtc_registration_number;
    }
    
    public void setDdtc_registration_number(java.lang.String ddtc_registration_number) {
        this.ddtc_registration_number = ddtc_registration_number;
    }
    
    public java.lang.Boolean getDdtc_sme() {
        return ddtc_sme;
    }
    
    public void setDdtc_sme(java.lang.Boolean ddtc_sme) {
        this.ddtc_sme = ddtc_sme;
    }
    
    public java.lang.String getDdtc_unit_measure() {
        return ddtc_unit_measure;
    }
    
    public void setDdtc_unit_measure(java.lang.String ddtc_unit_measure) {
        this.ddtc_unit_measure = ddtc_unit_measure;
    }
    
    public java.lang.String getDdtc_usml_category_code() {
        return ddtc_usml_category_code;
    }
    
    public void setDdtc_usml_category_code(java.lang.String ddtc_usml_category_code) {
        this.ddtc_usml_category_code = ddtc_usml_category_code;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public java.lang.String getEccn() {
        return eccn;
    }
    
    public void setEccn(java.lang.String eccn) {
        this.eccn = eccn;
    }
    
    public java.lang.String getExport_harmonized_code() {
        return export_harmonized_code;
    }
    
    public void setExport_harmonized_code(java.lang.String export_harmonized_code) {
        this.export_harmonized_code = export_harmonized_code;
    }
    
    public java.lang.String getExport_information_code() {
        return export_information_code;
    }
    
    public void setExport_information_code(java.lang.String export_information_code) {
        this.export_information_code = export_information_code;
    }
    
    public java.math.BigDecimal getExport_quantity_1() {
        return export_quantity_1;
    }
    
    public void setExport_quantity_1(java.math.BigDecimal export_quantity_1) {
        this.export_quantity_1 = export_quantity_1;
    }
    
    public java.math.BigDecimal getExport_quantity_2() {
        return export_quantity_2;
    }
    
    public void setExport_quantity_2(java.math.BigDecimal export_quantity_2) {
        this.export_quantity_2 = export_quantity_2;
    }
    
    public java.lang.String getExport_quantity_unit_measure_1() {
        return export_quantity_unit_measure_1;
    }
    
    public void setExport_quantity_unit_measure_1(java.lang.String export_quantity_unit_measure_1) {
        this.export_quantity_unit_measure_1 = export_quantity_unit_measure_1;
    }
    
    public java.lang.String getExport_quantity_unit_measure_2() {
        return export_quantity_unit_measure_2;
    }
    
    public void setExport_quantity_unit_measure_2(java.lang.String export_quantity_unit_measure_2) {
        this.export_quantity_unit_measure_2 = export_quantity_unit_measure_2;
    }
    
    public java.lang.String getHarmonized_code() {
        return harmonized_code;
    }
    
    public void setHarmonized_code(java.lang.String harmonized_code) {
        this.harmonized_code = harmonized_code;
    }
    
    public java.lang.String getLicense_expiration_date() {
        return license_expiration_date;
    }
    
    public void setLicense_expiration_date(java.lang.String license_expiration_date) {
        this.license_expiration_date = license_expiration_date;
    }
    
    public java.lang.String getLicense_number() {
        return license_number;
    }
    
    public void setLicense_number(java.lang.String license_number) {
        this.license_number = license_number;
    }
    
    public java.lang.String getLicense_type() {
        return license_type;
    }
    
    public void setLicense_type(java.lang.String license_type) {
        this.license_type = license_type;
    }
    
    public java.math.BigDecimal getLicense_unit_value() {
        return license_unit_value;
    }
    
    public void setLicense_unit_value(java.math.BigDecimal license_unit_value) {
        this.license_unit_value = license_unit_value;
    }
    
    public java.lang.String getLicense_unit_value_unit() {
        return license_unit_value_unit;
    }
    
    public void setLicense_unit_value_unit(java.lang.String license_unit_value_unit) {
        this.license_unit_value_unit = license_unit_value_unit;
    }
    
    public java.lang.String getManufacturer_id() {
        return manufacturer_id;
    }
    
    public void setManufacturer_id(java.lang.String manufacturer_id) {
        this.manufacturer_id = manufacturer_id;
    }
    
    public java.lang.Integer getNafta_preference_criterion() {
        return nafta_preference_criterion;
    }
    
    public void setNafta_preference_criterion(java.lang.Integer nafta_preference_criterion) {
        this.nafta_preference_criterion = nafta_preference_criterion;
    }
    
    public java.lang.Integer getNafta_producer() {
        return nafta_producer;
    }
    
    public void setNafta_producer(java.lang.Integer nafta_producer) {
        this.nafta_producer = nafta_producer;
    }
    
    public java.lang.String getNafta_rvc_avg_end_date() {
        return nafta_rvc_avg_end_date;
    }
    
    public void setNafta_rvc_avg_end_date(java.lang.String nafta_rvc_avg_end_date) {
        this.nafta_rvc_avg_end_date = nafta_rvc_avg_end_date;
    }
    
    public java.lang.String getNafta_rvc_avg_start_date() {
        return nafta_rvc_avg_start_date;
    }
    
    public void setNafta_rvc_avg_start_date(java.lang.String nafta_rvc_avg_start_date) {
        this.nafta_rvc_avg_start_date = nafta_rvc_avg_start_date;
    }
    
    public java.lang.Integer getNafta_rvc_method() {
        return nafta_rvc_method;
    }
    
    public void setNafta_rvc_method(java.lang.Integer nafta_rvc_method) {
        this.nafta_rvc_method = nafta_rvc_method;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.NameAddress getOrigin() {
        return origin;
    }
    
    public void setOrigin(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.NameAddress origin) {
        this.origin = origin;
    }
    
    public java.lang.String getOrigin_country() {
        return origin_country;
    }
    
    public void setOrigin_country(java.lang.String origin_country) {
        this.origin_country = origin_country;
    }
    
    public java.lang.String getOrigin_description() {
        return origin_description;
    }
    
    public void setOrigin_description(java.lang.String origin_description) {
        this.origin_description = origin_description;
    }
    
    public java.lang.String getOrigin_tax_id() {
        return origin_tax_id;
    }
    
    public void setOrigin_tax_id(java.lang.String origin_tax_id) {
        this.origin_tax_id = origin_tax_id;
    }
    
    public java.lang.String getProduct_code() {
        return product_code;
    }
    
    public void setProduct_code(java.lang.String product_code) {
        this.product_code = product_code;
    }
    
    public java.lang.Long getQuantity() {
        return quantity;
    }
    
    public void setQuantity(java.lang.Long quantity) {
        this.quantity = quantity;
    }
    
    public java.lang.String getQuantity_unit_measure() {
        return quantity_unit_measure;
    }
    
    public void setQuantity_unit_measure(java.lang.String quantity_unit_measure) {
        this.quantity_unit_measure = quantity_unit_measure;
    }
    
    public java.lang.Integer getRestricted_article_type() {
        return restricted_article_type;
    }
    
    public void setRestricted_article_type(java.lang.Integer restricted_article_type) {
        this.restricted_article_type = restricted_article_type;
    }
    
    public java.lang.Integer getSed_method() {
        return sed_method;
    }
    
    public void setSed_method(java.lang.Integer sed_method) {
        this.sed_method = sed_method;
    }
    
    public java.math.BigDecimal getUnit_value() {
        return unit_value;
    }
    
    public void setUnit_value(java.math.BigDecimal unit_value) {
        this.unit_value = unit_value;
    }
    
    public java.lang.String getUnit_value_unit() {
        return unit_value_unit;
    }
    
    public void setUnit_value_unit(java.lang.String unit_value_unit) {
        this.unit_value_unit = unit_value_unit;
    }
    
    public java.math.BigDecimal getUnit_weight() {
        return unit_weight;
    }
    
    public void setUnit_weight(java.math.BigDecimal unit_weight) {
        this.unit_weight = unit_weight;
    }
    
    public java.lang.String getUnit_weight_unit() {
        return unit_weight_unit;
    }
    
    public void setUnit_weight_unit(java.lang.String unit_weight_unit) {
        this.unit_weight_unit = unit_weight_unit;
    }
}
