// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class DeleteAddressRecordbyUserResponse implements java.io.Serializable {
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxReturn deleteAddressRecordbyUserResult;
    
    public DeleteAddressRecordbyUserResponse() {
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxReturn getDeleteAddressRecordbyUserResult() {
        return deleteAddressRecordbyUserResult;
    }
    
    public void setDeleteAddressRecordbyUserResult(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxReturn deleteAddressRecordbyUserResult) {
        this.deleteAddressRecordbyUserResult = deleteAddressRecordbyUserResult;
    }
}
