// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class GetPrinter implements java.io.Serializable {
    protected int printer_id;
    
    public GetPrinter() {
    }
    
    public int getPrinter_id() {
        return printer_id;
    }
    
    public void setPrinter_id(int printer_id) {
        this.printer_id = printer_id;
    }
}
