// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class HazMatContent implements java.io.Serializable {
    protected java.lang.Boolean hazmat_500Kg_exemption;
    protected java.lang.Boolean hazmat_accessible;
    protected java.lang.Integer hazmat_ca_category;
    protected java.lang.Boolean hazmat_cargo;
    protected java.lang.String hazmat_class;
    protected java.lang.String hazmat_description;
    protected java.lang.String hazmat_emergency_contact;
    protected java.lang.String hazmat_emergency_phone;
    protected java.lang.String hazmat_ex_number;
    protected java.lang.Boolean hazmat_excepted_quantity;
    protected java.lang.String hazmat_id;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.NameAddress hazmat_infectious_responsible_party;
    protected java.lang.Integer hazmat_label;
    protected java.lang.Boolean hazmat_limited_quantity;
    protected java.lang.String hazmat_packing;
    protected java.lang.Integer hazmat_packing_group;
    protected java.lang.String hazmat_packing_instruction;
    protected java.math.BigDecimal hazmat_percentage;
    protected java.math.BigDecimal hazmat_quantity;
    protected java.lang.String hazmat_quantity_unit;
    protected java.math.BigDecimal hazmat_radioactive_activity;
    protected java.lang.String hazmat_radioactive_activity_unit;
    protected java.lang.String hazmat_radioactive_chemical_form;
    protected java.math.BigDecimal hazmat_radioactive_csi;
    protected java.lang.Integer hazmat_radioactive_exception;
    protected java.lang.String hazmat_radioactive_name;
    protected java.lang.String hazmat_radioactive_packaging;
    protected java.lang.Integer hazmat_radioactive_physical_form;
    protected java.math.BigDecimal hazmat_radioactive_surface_reading;
    protected java.lang.String hazmat_radioactive_surface_reading_unit;
    protected java.math.BigDecimal hazmat_radioactive_transport_index;
    protected java.lang.String hazmat_reference;
    protected java.lang.Integer hazmat_regulation;
    protected java.lang.Integer hazmat_regulation_set;
    protected java.lang.Boolean hazmat_reportable_quantity;
    protected java.lang.String hazmat_special_provisions;
    protected java.lang.String hazmat_subsidiary_risk_class;
    protected java.lang.String hazmat_technical_name;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_1;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_2;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_3;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_4;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_5;
    
    public HazMatContent() {
    }
    
    public java.lang.Boolean getHazmat_500Kg_exemption() {
        return hazmat_500Kg_exemption;
    }
    
    public void setHazmat_500Kg_exemption(java.lang.Boolean hazmat_500Kg_exemption) {
        this.hazmat_500Kg_exemption = hazmat_500Kg_exemption;
    }
    
    public java.lang.Boolean getHazmat_accessible() {
        return hazmat_accessible;
    }
    
    public void setHazmat_accessible(java.lang.Boolean hazmat_accessible) {
        this.hazmat_accessible = hazmat_accessible;
    }
    
    public java.lang.Integer getHazmat_ca_category() {
        return hazmat_ca_category;
    }
    
    public void setHazmat_ca_category(java.lang.Integer hazmat_ca_category) {
        this.hazmat_ca_category = hazmat_ca_category;
    }
    
    public java.lang.Boolean getHazmat_cargo() {
        return hazmat_cargo;
    }
    
    public void setHazmat_cargo(java.lang.Boolean hazmat_cargo) {
        this.hazmat_cargo = hazmat_cargo;
    }
    
    public java.lang.String getHazmat_class() {
        return hazmat_class;
    }
    
    public void setHazmat_class(java.lang.String hazmat_class) {
        this.hazmat_class = hazmat_class;
    }
    
    public java.lang.String getHazmat_description() {
        return hazmat_description;
    }
    
    public void setHazmat_description(java.lang.String hazmat_description) {
        this.hazmat_description = hazmat_description;
    }
    
    public java.lang.String getHazmat_emergency_contact() {
        return hazmat_emergency_contact;
    }
    
    public void setHazmat_emergency_contact(java.lang.String hazmat_emergency_contact) {
        this.hazmat_emergency_contact = hazmat_emergency_contact;
    }
    
    public java.lang.String getHazmat_emergency_phone() {
        return hazmat_emergency_phone;
    }
    
    public void setHazmat_emergency_phone(java.lang.String hazmat_emergency_phone) {
        this.hazmat_emergency_phone = hazmat_emergency_phone;
    }
    
    public java.lang.String getHazmat_ex_number() {
        return hazmat_ex_number;
    }
    
    public void setHazmat_ex_number(java.lang.String hazmat_ex_number) {
        this.hazmat_ex_number = hazmat_ex_number;
    }
    
    public java.lang.Boolean getHazmat_excepted_quantity() {
        return hazmat_excepted_quantity;
    }
    
    public void setHazmat_excepted_quantity(java.lang.Boolean hazmat_excepted_quantity) {
        this.hazmat_excepted_quantity = hazmat_excepted_quantity;
    }
    
    public java.lang.String getHazmat_id() {
        return hazmat_id;
    }
    
    public void setHazmat_id(java.lang.String hazmat_id) {
        this.hazmat_id = hazmat_id;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.NameAddress getHazmat_infectious_responsible_party() {
        return hazmat_infectious_responsible_party;
    }
    
    public void setHazmat_infectious_responsible_party(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.NameAddress hazmat_infectious_responsible_party) {
        this.hazmat_infectious_responsible_party = hazmat_infectious_responsible_party;
    }
    
    public java.lang.Integer getHazmat_label() {
        return hazmat_label;
    }
    
    public void setHazmat_label(java.lang.Integer hazmat_label) {
        this.hazmat_label = hazmat_label;
    }
    
    public java.lang.Boolean getHazmat_limited_quantity() {
        return hazmat_limited_quantity;
    }
    
    public void setHazmat_limited_quantity(java.lang.Boolean hazmat_limited_quantity) {
        this.hazmat_limited_quantity = hazmat_limited_quantity;
    }
    
    public java.lang.String getHazmat_packing() {
        return hazmat_packing;
    }
    
    public void setHazmat_packing(java.lang.String hazmat_packing) {
        this.hazmat_packing = hazmat_packing;
    }
    
    public java.lang.Integer getHazmat_packing_group() {
        return hazmat_packing_group;
    }
    
    public void setHazmat_packing_group(java.lang.Integer hazmat_packing_group) {
        this.hazmat_packing_group = hazmat_packing_group;
    }
    
    public java.lang.String getHazmat_packing_instruction() {
        return hazmat_packing_instruction;
    }
    
    public void setHazmat_packing_instruction(java.lang.String hazmat_packing_instruction) {
        this.hazmat_packing_instruction = hazmat_packing_instruction;
    }
    
    public java.math.BigDecimal getHazmat_percentage() {
        return hazmat_percentage;
    }
    
    public void setHazmat_percentage(java.math.BigDecimal hazmat_percentage) {
        this.hazmat_percentage = hazmat_percentage;
    }
    
    public java.math.BigDecimal getHazmat_quantity() {
        return hazmat_quantity;
    }
    
    public void setHazmat_quantity(java.math.BigDecimal hazmat_quantity) {
        this.hazmat_quantity = hazmat_quantity;
    }
    
    public java.lang.String getHazmat_quantity_unit() {
        return hazmat_quantity_unit;
    }
    
    public void setHazmat_quantity_unit(java.lang.String hazmat_quantity_unit) {
        this.hazmat_quantity_unit = hazmat_quantity_unit;
    }
    
    public java.math.BigDecimal getHazmat_radioactive_activity() {
        return hazmat_radioactive_activity;
    }
    
    public void setHazmat_radioactive_activity(java.math.BigDecimal hazmat_radioactive_activity) {
        this.hazmat_radioactive_activity = hazmat_radioactive_activity;
    }
    
    public java.lang.String getHazmat_radioactive_activity_unit() {
        return hazmat_radioactive_activity_unit;
    }
    
    public void setHazmat_radioactive_activity_unit(java.lang.String hazmat_radioactive_activity_unit) {
        this.hazmat_radioactive_activity_unit = hazmat_radioactive_activity_unit;
    }
    
    public java.lang.String getHazmat_radioactive_chemical_form() {
        return hazmat_radioactive_chemical_form;
    }
    
    public void setHazmat_radioactive_chemical_form(java.lang.String hazmat_radioactive_chemical_form) {
        this.hazmat_radioactive_chemical_form = hazmat_radioactive_chemical_form;
    }
    
    public java.math.BigDecimal getHazmat_radioactive_csi() {
        return hazmat_radioactive_csi;
    }
    
    public void setHazmat_radioactive_csi(java.math.BigDecimal hazmat_radioactive_csi) {
        this.hazmat_radioactive_csi = hazmat_radioactive_csi;
    }
    
    public java.lang.Integer getHazmat_radioactive_exception() {
        return hazmat_radioactive_exception;
    }
    
    public void setHazmat_radioactive_exception(java.lang.Integer hazmat_radioactive_exception) {
        this.hazmat_radioactive_exception = hazmat_radioactive_exception;
    }
    
    public java.lang.String getHazmat_radioactive_name() {
        return hazmat_radioactive_name;
    }
    
    public void setHazmat_radioactive_name(java.lang.String hazmat_radioactive_name) {
        this.hazmat_radioactive_name = hazmat_radioactive_name;
    }
    
    public java.lang.String getHazmat_radioactive_packaging() {
        return hazmat_radioactive_packaging;
    }
    
    public void setHazmat_radioactive_packaging(java.lang.String hazmat_radioactive_packaging) {
        this.hazmat_radioactive_packaging = hazmat_radioactive_packaging;
    }
    
    public java.lang.Integer getHazmat_radioactive_physical_form() {
        return hazmat_radioactive_physical_form;
    }
    
    public void setHazmat_radioactive_physical_form(java.lang.Integer hazmat_radioactive_physical_form) {
        this.hazmat_radioactive_physical_form = hazmat_radioactive_physical_form;
    }
    
    public java.math.BigDecimal getHazmat_radioactive_surface_reading() {
        return hazmat_radioactive_surface_reading;
    }
    
    public void setHazmat_radioactive_surface_reading(java.math.BigDecimal hazmat_radioactive_surface_reading) {
        this.hazmat_radioactive_surface_reading = hazmat_radioactive_surface_reading;
    }
    
    public java.lang.String getHazmat_radioactive_surface_reading_unit() {
        return hazmat_radioactive_surface_reading_unit;
    }
    
    public void setHazmat_radioactive_surface_reading_unit(java.lang.String hazmat_radioactive_surface_reading_unit) {
        this.hazmat_radioactive_surface_reading_unit = hazmat_radioactive_surface_reading_unit;
    }
    
    public java.math.BigDecimal getHazmat_radioactive_transport_index() {
        return hazmat_radioactive_transport_index;
    }
    
    public void setHazmat_radioactive_transport_index(java.math.BigDecimal hazmat_radioactive_transport_index) {
        this.hazmat_radioactive_transport_index = hazmat_radioactive_transport_index;
    }
    
    public java.lang.String getHazmat_reference() {
        return hazmat_reference;
    }
    
    public void setHazmat_reference(java.lang.String hazmat_reference) {
        this.hazmat_reference = hazmat_reference;
    }
    
    public java.lang.Integer getHazmat_regulation() {
        return hazmat_regulation;
    }
    
    public void setHazmat_regulation(java.lang.Integer hazmat_regulation) {
        this.hazmat_regulation = hazmat_regulation;
    }
    
    public java.lang.Integer getHazmat_regulation_set() {
        return hazmat_regulation_set;
    }
    
    public void setHazmat_regulation_set(java.lang.Integer hazmat_regulation_set) {
        this.hazmat_regulation_set = hazmat_regulation_set;
    }
    
    public java.lang.Boolean getHazmat_reportable_quantity() {
        return hazmat_reportable_quantity;
    }
    
    public void setHazmat_reportable_quantity(java.lang.Boolean hazmat_reportable_quantity) {
        this.hazmat_reportable_quantity = hazmat_reportable_quantity;
    }
    
    public java.lang.String getHazmat_special_provisions() {
        return hazmat_special_provisions;
    }
    
    public void setHazmat_special_provisions(java.lang.String hazmat_special_provisions) {
        this.hazmat_special_provisions = hazmat_special_provisions;
    }
    
    public java.lang.String getHazmat_subsidiary_risk_class() {
        return hazmat_subsidiary_risk_class;
    }
    
    public void setHazmat_subsidiary_risk_class(java.lang.String hazmat_subsidiary_risk_class) {
        this.hazmat_subsidiary_risk_class = hazmat_subsidiary_risk_class;
    }
    
    public java.lang.String getHazmat_technical_name() {
        return hazmat_technical_name;
    }
    
    public void setHazmat_technical_name(java.lang.String hazmat_technical_name) {
        this.hazmat_technical_name = hazmat_technical_name;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] getUser_data_1() {
        return user_data_1;
    }
    
    public void setUser_data_1(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_1) {
        this.user_data_1 = user_data_1;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] getUser_data_2() {
        return user_data_2;
    }
    
    public void setUser_data_2(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_2) {
        this.user_data_2 = user_data_2;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] getUser_data_3() {
        return user_data_3;
    }
    
    public void setUser_data_3(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_3) {
        this.user_data_3 = user_data_3;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] getUser_data_4() {
        return user_data_4;
    }
    
    public void setUser_data_4(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_4) {
        this.user_data_4 = user_data_4;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] getUser_data_5() {
        return user_data_5;
    }
    
    public void setUser_data_5(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] user_data_5) {
        this.user_data_5 = user_data_5;
    }
}
