// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class PackResponseBase extends com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ErrorBase implements java.io.Serializable {
    protected java.lang.String order_reference;
    
    public PackResponseBase() {
    }
    
    public java.lang.String getOrder_reference() {
        return order_reference;
    }
    
    public void setOrder_reference(java.lang.String order_reference) {
        this.order_reference = order_reference;
    }
}
