// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class PackRateType implements java.io.Serializable {
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRateRequest packRateRequest;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] params;
    
    public PackRateType() {
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRateRequest getPackRateRequest() {
        return packRateRequest;
    }
    
    public void setPackRateRequest(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRateRequest packRateRequest) {
        this.packRateRequest = packRateRequest;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] getParams() {
        return params;
    }
    
    public void setParams(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDictionaryItem[] params) {
        this.params = params;
    }
}
