// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class PackRequest extends com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRequestBase implements java.io.Serializable {
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Warehouse[] warehouses;
    
    public PackRequest() {
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Warehouse[] getWarehouses() {
        return warehouses;
    }
    
    public void setWarehouses(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Warehouse[] warehouses) {
        this.warehouses = warehouses;
    }
}
