// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class SearchByShipperReferenceWithCountResponse implements java.io.Serializable {
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Package[] searchByShipperReferenceWithCountResult;
    
    public SearchByShipperReferenceWithCountResponse() {
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Package[] getSearchByShipperReferenceWithCountResult() {
        return searchByShipperReferenceWithCountResult;
    }
    
    public void setSearchByShipperReferenceWithCountResult(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Package[] searchByShipperReferenceWithCountResult) {
        this.searchByShipperReferenceWithCountResult = searchByShipperReferenceWithCountResult;
    }
}
