// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class Sox_Db_VersionResponse implements java.io.Serializable {
    protected java.lang.String sox_Db_VersionResult;
    
    public Sox_Db_VersionResponse() {
    }
    
    public java.lang.String getSox_Db_VersionResult() {
        return sox_Db_VersionResult;
    }
    
    public void setSox_Db_VersionResult(java.lang.String sox_Db_VersionResult) {
        this.sox_Db_VersionResult = sox_Db_VersionResult;
    }
}
