// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class SoxCountry implements java.io.Serializable {
    protected java.lang.String symbol;
    protected java.lang.String friendlyName;
    protected java.lang.String ISO2;
    protected java.lang.String ISO3;
    protected java.lang.Integer ISO3Number;
    protected java.lang.String IATA;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxCurrency currency;
    
    public SoxCountry() {
    }
    
    public java.lang.String getSymbol() {
        return symbol;
    }
    
    public void setSymbol(java.lang.String symbol) {
        this.symbol = symbol;
    }
    
    public java.lang.String getFriendlyName() {
        return friendlyName;
    }
    
    public void setFriendlyName(java.lang.String friendlyName) {
        this.friendlyName = friendlyName;
    }
    
    public java.lang.String getISO2() {
        return ISO2;
    }
    
    public void setISO2(java.lang.String ISO2) {
        this.ISO2 = ISO2;
    }
    
    public java.lang.String getISO3() {
        return ISO3;
    }
    
    public void setISO3(java.lang.String ISO3) {
        this.ISO3 = ISO3;
    }
    
    public java.lang.Integer getISO3Number() {
        return ISO3Number;
    }
    
    public void setISO3Number(java.lang.Integer ISO3Number) {
        this.ISO3Number = ISO3Number;
    }
    
    public java.lang.String getIATA() {
        return IATA;
    }
    
    public void setIATA(java.lang.String IATA) {
        this.IATA = IATA;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxCurrency getCurrency() {
        return currency;
    }
    
    public void setCurrency(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxCurrency currency) {
        this.currency = currency;
    }
}
