// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class SoxScale implements java.io.Serializable {
    protected java.lang.String model;
    protected java.lang.String port;
    protected boolean enabled;
    protected java.lang.String name;
    protected java.lang.String usbVid;
    protected java.lang.String usbPid;
    protected int baudRate;
    protected int dataBits;
    protected java.lang.String parity;
    protected java.lang.String stopBits;
    protected java.lang.String requestCommand;
    protected int requestTimeout;
    
    public SoxScale() {
    }
    
    public java.lang.String getModel() {
        return model;
    }
    
    public void setModel(java.lang.String model) {
        this.model = model;
    }
    
    public java.lang.String getPort() {
        return port;
    }
    
    public void setPort(java.lang.String port) {
        this.port = port;
    }
    
    public boolean isEnabled() {
        return enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getUsbVid() {
        return usbVid;
    }
    
    public void setUsbVid(java.lang.String usbVid) {
        this.usbVid = usbVid;
    }
    
    public java.lang.String getUsbPid() {
        return usbPid;
    }
    
    public void setUsbPid(java.lang.String usbPid) {
        this.usbPid = usbPid;
    }
    
    public int getBaudRate() {
        return baudRate;
    }
    
    public void setBaudRate(int baudRate) {
        this.baudRate = baudRate;
    }
    
    public int getDataBits() {
        return dataBits;
    }
    
    public void setDataBits(int dataBits) {
        this.dataBits = dataBits;
    }
    
    public java.lang.String getParity() {
        return parity;
    }
    
    public void setParity(java.lang.String parity) {
        this.parity = parity;
    }
    
    public java.lang.String getStopBits() {
        return stopBits;
    }
    
    public void setStopBits(java.lang.String stopBits) {
        this.stopBits = stopBits;
    }
    
    public java.lang.String getRequestCommand() {
        return requestCommand;
    }
    
    public void setRequestCommand(java.lang.String requestCommand) {
        this.requestCommand = requestCommand;
    }
    
    public int getRequestTimeout() {
        return requestTimeout;
    }
    
    public void setRequestTimeout(int requestTimeout) {
        this.requestTimeout = requestTimeout;
    }
}
