// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class Validate implements java.io.Serializable {
    protected java.lang.String user_name;
    protected java.lang.String password;
    
    public Validate() {
    }
    
    public java.lang.String getUser_name() {
        return user_name;
    }
    
    public void setUser_name(java.lang.String user_name) {
        this.user_name = user_name;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
}
