// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf;


public class WarehouseBase implements java.io.Serializable {
    protected java.lang.String warehouse_code;
    protected com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Container[] available_containers;
    
    public WarehouseBase() {
    }
    
    public java.lang.String getWarehouse_code() {
        return warehouse_code;
    }
    
    public void setWarehouse_code(java.lang.String warehouse_code) {
        this.warehouse_code = warehouse_code;
    }
    
    public com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Container[] getAvailable_containers() {
        return available_containers;
    }
    
    public void setAvailable_containers(com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Container[] available_containers) {
        this.available_containers = available_containers;
    }
}
