// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.literal.DetailFragmentDeserializer;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class ErrorBase_InterfaceSOAPSerializer extends InterfaceSerializerBase implements Initializable {
    private static final QName ns1_BatchRequest_TYPE_QNAME = new QName("http://PSI.Wcf", "BatchRequest");
    private CombinedSerializer myns1_BatchRequest__BatchRequest_LiteralSerializer;
    private static final QName ns1_BatchResponse_TYPE_QNAME = new QName("http://PSI.Wcf", "BatchResponse");
    private CombinedSerializer myns1_BatchResponse__BatchResponse_LiteralSerializer;
    private static final QName ns1_BatchBase_TYPE_QNAME = new QName("http://PSI.Wcf", "BatchBase");
    private CombinedSerializer myns1_BatchBase__BatchBase_InterfaceSOAPSerializer;
    private static final QName ns1_BatchRequestItem_TYPE_QNAME = new QName("http://PSI.Wcf", "BatchRequestItem");
    private CombinedSerializer myns1_BatchRequestItem__BatchRequestItem_LiteralSerializer;
    private static final QName ns1_BatchResponseItem_TYPE_QNAME = new QName("http://PSI.Wcf", "BatchResponseItem");
    private CombinedSerializer myns1_BatchResponseItem__BatchResponseItem_LiteralSerializer;
    private static final QName ns1_BatchItemBase_TYPE_QNAME = new QName("http://PSI.Wcf", "BatchItemBase");
    private CombinedSerializer myns1_BatchItemBase__BatchItemBase_InterfaceSOAPSerializer;
    private static final QName ns1_CloseGroupResponse_TYPE_QNAME = new QName("http://PSI.Wcf", "CloseGroupResponse");
    private CombinedSerializer myns1_CloseGroupResponse__CloseGroupResponse_LiteralSerializer;
    private static final QName ns1_CloseOutResult_TYPE_QNAME = new QName("http://PSI.Wcf", "CloseOutResult");
    private CombinedSerializer myns1_CloseOutResult__CloseOutResult_LiteralSerializer;
    private static final QName ns1_CompoundError_TYPE_QNAME = new QName("http://PSI.Wcf", "CompoundError");
    private CombinedSerializer myns1_CompoundError__CompoundError_LiteralSerializer;
    private static final QName ns1_Package_TYPE_QNAME = new QName("http://PSI.Wcf", "Package");
    private CombinedSerializer myns1_Package__Package_LiteralSerializer;
    private static final QName ns1_CompoundErrorBase_TYPE_QNAME = new QName("http://PSI.Wcf", "CompoundErrorBase");
    private CombinedSerializer myns1_CompoundErrorBase__CompoundErrorBase_InterfaceSOAPSerializer;
    private static final QName ns1_Group_TYPE_QNAME = new QName("http://PSI.Wcf", "Group");
    private CombinedSerializer myns1_Group__Group_LiteralSerializer;
    private static final QName ns1_Grouping_TYPE_QNAME = new QName("http://PSI.Wcf", "Grouping");
    private CombinedSerializer myns1_Grouping__Grouping_LiteralSerializer;
    private static final QName ns1_LicenseValidationResponse_TYPE_QNAME = new QName("http://PSI.Wcf", "LicenseValidationResponse");
    private CombinedSerializer myns1_LicenseValidationResponse__LicenseValidationResponse_LiteralSerializer;
    private static final QName ns1_ModifyPackageListResult_TYPE_QNAME = new QName("http://PSI.Wcf", "ModifyPackageListResult");
    private CombinedSerializer myns1_ModifyPackageListResult__ModifyPackageListResult_LiteralSerializer;
    private static final QName ns1_ModifyPackageResult_TYPE_QNAME = new QName("http://PSI.Wcf", "ModifyPackageResult");
    private CombinedSerializer myns1_ModifyPackageResult__ModifyPackageResult_LiteralSerializer;
    private static final QName ns1_PackDetail_TYPE_QNAME = new QName("http://PSI.Wcf", "PackDetail");
    private CombinedSerializer myns1_PackDetail__PackDetail_LiteralSerializer;
    private static final QName ns1_PackDetailBase_TYPE_QNAME = new QName("http://PSI.Wcf", "PackDetailBase");
    private CombinedSerializer myns1_PackDetailBase__PackDetailBase_InterfaceSOAPSerializer;
    private static final QName ns1_PackOrderLineError_TYPE_QNAME = new QName("http://PSI.Wcf", "PackOrderLineError");
    private CombinedSerializer myns1_PackOrderLineError__PackOrderLineError_LiteralSerializer;
    private static final QName ns1_PackRateDetail_TYPE_QNAME = new QName("http://PSI.Wcf", "PackRateDetail");
    private CombinedSerializer myns1_PackRateDetail__PackRateDetail_LiteralSerializer;
    private static final QName ns1_PackRateResponse_TYPE_QNAME = new QName("http://PSI.Wcf", "PackRateResponse");
    private CombinedSerializer myns1_PackRateResponse__PackRateResponse_LiteralSerializer;
    private static final QName ns1_PackResponse_TYPE_QNAME = new QName("http://PSI.Wcf", "PackResponse");
    private CombinedSerializer myns1_PackResponse__PackResponse_LiteralSerializer;
    private static final QName ns1_PackResponseBase_TYPE_QNAME = new QName("http://PSI.Wcf", "PackResponseBase");
    private CombinedSerializer myns1_PackResponseBase__PackResponseBase_InterfaceSOAPSerializer;
    private static final QName ns1_PackageRequest_TYPE_QNAME = new QName("http://PSI.Wcf", "PackageRequest");
    private CombinedSerializer myns1_PackageRequest__PackageRequest_LiteralSerializer;
    private static final QName ns1_PackageResponse_TYPE_QNAME = new QName("http://PSI.Wcf", "PackageResponse");
    private CombinedSerializer myns1_PackageResponse__PackageResponse_LiteralSerializer;
    private static final QName ns1_ReProcessResponse_TYPE_QNAME = new QName("http://PSI.Wcf", "ReProcessResponse");
    private CombinedSerializer myns1_ReProcessResponse__ReProcessResponse_LiteralSerializer;
    private static final QName ns1_SoxDocument_TYPE_QNAME = new QName("http://PSI.Wcf", "SoxDocument");
    private CombinedSerializer myns1_SoxDocument__SoxDocument_LiteralSerializer;
    private static final QName ns1_SoxReturn_TYPE_QNAME = new QName("http://PSI.Wcf", "SoxReturn");
    private CombinedSerializer myns1_SoxReturn__SoxReturn_LiteralSerializer;
    private CombinedSerializer myns1_ErrorBase__ErrorBase_LiteralSerializer;
    
    public ErrorBase_InterfaceSOAPSerializer(QName type, boolean encodeType, boolean isNullable, SOAPVersion soapVersion) {
        super(type, encodeType, isNullable, soapVersion);
    }
    public ErrorBase_InterfaceSOAPSerializer(QName type, boolean encodeType) {
        super(type, encodeType, true, null);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns1_BatchRequest__BatchRequest_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.BatchRequest.class, ns1_BatchRequest_TYPE_QNAME);
        myns1_BatchRequest__BatchRequest_LiteralSerializer = myns1_BatchRequest__BatchRequest_LiteralSerializer.getInnermostSerializer();
        myns1_BatchResponse__BatchResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.BatchResponse.class, ns1_BatchResponse_TYPE_QNAME);
        myns1_BatchResponse__BatchResponse_LiteralSerializer = myns1_BatchResponse__BatchResponse_LiteralSerializer.getInnermostSerializer();
        myns1_BatchBase__BatchBase_InterfaceSOAPSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.BatchBase.class, ns1_BatchBase_TYPE_QNAME);
        myns1_BatchBase__BatchBase_InterfaceSOAPSerializer = myns1_BatchBase__BatchBase_InterfaceSOAPSerializer.getInnermostSerializer();
        myns1_BatchRequestItem__BatchRequestItem_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.BatchRequestItem.class, ns1_BatchRequestItem_TYPE_QNAME);
        myns1_BatchRequestItem__BatchRequestItem_LiteralSerializer = myns1_BatchRequestItem__BatchRequestItem_LiteralSerializer.getInnermostSerializer();
        myns1_BatchResponseItem__BatchResponseItem_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.BatchResponseItem.class, ns1_BatchResponseItem_TYPE_QNAME);
        myns1_BatchResponseItem__BatchResponseItem_LiteralSerializer = myns1_BatchResponseItem__BatchResponseItem_LiteralSerializer.getInnermostSerializer();
        myns1_BatchItemBase__BatchItemBase_InterfaceSOAPSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.BatchItemBase.class, ns1_BatchItemBase_TYPE_QNAME);
        myns1_BatchItemBase__BatchItemBase_InterfaceSOAPSerializer = myns1_BatchItemBase__BatchItemBase_InterfaceSOAPSerializer.getInnermostSerializer();
        myns1_CloseGroupResponse__CloseGroupResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CloseGroupResponse.class, ns1_CloseGroupResponse_TYPE_QNAME);
        myns1_CloseGroupResponse__CloseGroupResponse_LiteralSerializer = myns1_CloseGroupResponse__CloseGroupResponse_LiteralSerializer.getInnermostSerializer();
        myns1_CloseOutResult__CloseOutResult_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CloseOutResult.class, ns1_CloseOutResult_TYPE_QNAME);
        myns1_CloseOutResult__CloseOutResult_LiteralSerializer = myns1_CloseOutResult__CloseOutResult_LiteralSerializer.getInnermostSerializer();
        myns1_CompoundError__CompoundError_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CompoundError.class, ns1_CompoundError_TYPE_QNAME);
        myns1_CompoundError__CompoundError_LiteralSerializer = myns1_CompoundError__CompoundError_LiteralSerializer.getInnermostSerializer();
        myns1_Package__Package_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Package.class, ns1_Package_TYPE_QNAME);
        myns1_Package__Package_LiteralSerializer = myns1_Package__Package_LiteralSerializer.getInnermostSerializer();
        myns1_CompoundErrorBase__CompoundErrorBase_InterfaceSOAPSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CompoundErrorBase.class, ns1_CompoundErrorBase_TYPE_QNAME);
        myns1_CompoundErrorBase__CompoundErrorBase_InterfaceSOAPSerializer = myns1_CompoundErrorBase__CompoundErrorBase_InterfaceSOAPSerializer.getInnermostSerializer();
        myns1_Group__Group_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Group.class, ns1_Group_TYPE_QNAME);
        myns1_Group__Group_LiteralSerializer = myns1_Group__Group_LiteralSerializer.getInnermostSerializer();
        myns1_Grouping__Grouping_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Grouping.class, ns1_Grouping_TYPE_QNAME);
        myns1_Grouping__Grouping_LiteralSerializer = myns1_Grouping__Grouping_LiteralSerializer.getInnermostSerializer();
        myns1_LicenseValidationResponse__LicenseValidationResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.LicenseValidationResponse.class, ns1_LicenseValidationResponse_TYPE_QNAME);
        myns1_LicenseValidationResponse__LicenseValidationResponse_LiteralSerializer = myns1_LicenseValidationResponse__LicenseValidationResponse_LiteralSerializer.getInnermostSerializer();
        myns1_ModifyPackageListResult__ModifyPackageListResult_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ModifyPackageListResult.class, ns1_ModifyPackageListResult_TYPE_QNAME);
        myns1_ModifyPackageListResult__ModifyPackageListResult_LiteralSerializer = myns1_ModifyPackageListResult__ModifyPackageListResult_LiteralSerializer.getInnermostSerializer();
        myns1_ModifyPackageResult__ModifyPackageResult_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ModifyPackageResult.class, ns1_ModifyPackageResult_TYPE_QNAME);
        myns1_ModifyPackageResult__ModifyPackageResult_LiteralSerializer = myns1_ModifyPackageResult__ModifyPackageResult_LiteralSerializer.getInnermostSerializer();
        myns1_PackDetail__PackDetail_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackDetail.class, ns1_PackDetail_TYPE_QNAME);
        myns1_PackDetail__PackDetail_LiteralSerializer = myns1_PackDetail__PackDetail_LiteralSerializer.getInnermostSerializer();
        myns1_PackDetailBase__PackDetailBase_InterfaceSOAPSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackDetailBase.class, ns1_PackDetailBase_TYPE_QNAME);
        myns1_PackDetailBase__PackDetailBase_InterfaceSOAPSerializer = myns1_PackDetailBase__PackDetailBase_InterfaceSOAPSerializer.getInnermostSerializer();
        myns1_PackOrderLineError__PackOrderLineError_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackOrderLineError.class, ns1_PackOrderLineError_TYPE_QNAME);
        myns1_PackOrderLineError__PackOrderLineError_LiteralSerializer = myns1_PackOrderLineError__PackOrderLineError_LiteralSerializer.getInnermostSerializer();
        myns1_PackRateDetail__PackRateDetail_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRateDetail.class, ns1_PackRateDetail_TYPE_QNAME);
        myns1_PackRateDetail__PackRateDetail_LiteralSerializer = myns1_PackRateDetail__PackRateDetail_LiteralSerializer.getInnermostSerializer();
        myns1_PackRateResponse__PackRateResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRateResponse.class, ns1_PackRateResponse_TYPE_QNAME);
        myns1_PackRateResponse__PackRateResponse_LiteralSerializer = myns1_PackRateResponse__PackRateResponse_LiteralSerializer.getInnermostSerializer();
        myns1_PackResponse__PackResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackResponse.class, ns1_PackResponse_TYPE_QNAME);
        myns1_PackResponse__PackResponse_LiteralSerializer = myns1_PackResponse__PackResponse_LiteralSerializer.getInnermostSerializer();
        myns1_PackResponseBase__PackResponseBase_InterfaceSOAPSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackResponseBase.class, ns1_PackResponseBase_TYPE_QNAME);
        myns1_PackResponseBase__PackResponseBase_InterfaceSOAPSerializer = myns1_PackResponseBase__PackResponseBase_InterfaceSOAPSerializer.getInnermostSerializer();
        myns1_PackageRequest__PackageRequest_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackageRequest.class, ns1_PackageRequest_TYPE_QNAME);
        myns1_PackageRequest__PackageRequest_LiteralSerializer = myns1_PackageRequest__PackageRequest_LiteralSerializer.getInnermostSerializer();
        myns1_PackageResponse__PackageResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackageResponse.class, ns1_PackageResponse_TYPE_QNAME);
        myns1_PackageResponse__PackageResponse_LiteralSerializer = myns1_PackageResponse__PackageResponse_LiteralSerializer.getInnermostSerializer();
        myns1_ReProcessResponse__ReProcessResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ReProcessResponse.class, ns1_ReProcessResponse_TYPE_QNAME);
        myns1_ReProcessResponse__ReProcessResponse_LiteralSerializer = myns1_ReProcessResponse__ReProcessResponse_LiteralSerializer.getInnermostSerializer();
        myns1_SoxDocument__SoxDocument_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDocument.class, ns1_SoxDocument_TYPE_QNAME);
        myns1_SoxDocument__SoxDocument_LiteralSerializer = myns1_SoxDocument__SoxDocument_LiteralSerializer.getInnermostSerializer();
        myns1_SoxReturn__SoxReturn_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxReturn.class, ns1_SoxReturn_TYPE_QNAME);
        myns1_SoxReturn__SoxReturn_LiteralSerializer = myns1_SoxReturn__SoxReturn_LiteralSerializer.getInnermostSerializer();
        QName type = new QName("http://PSI.Wcf", "ErrorBase");
        CombinedSerializer interfaceSerializer = new com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.runtime.ErrorBase_LiteralSerializer(type, DONT_ENCODE_TYPE);
        myns1_ErrorBase__ErrorBase_LiteralSerializer = interfaceSerializer.getInnermostSerializer();
        if (myns1_ErrorBase__ErrorBase_LiteralSerializer instanceof Initializable) {
            ((Initializable)myns1_ErrorBase__ErrorBase_LiteralSerializer).initialize(registry);
        }
    }
    
    public java.lang.Object doDeserialize(QName name, XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        QName elementType = getType(reader);
        if (elementType != null && elementType.equals(myns1_BatchRequest__BatchRequest_LiteralSerializer.getXmlType())) {
            return myns1_BatchRequest__BatchRequest_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_BatchResponse__BatchResponse_LiteralSerializer.getXmlType())) {
            return myns1_BatchResponse__BatchResponse_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_BatchBase__BatchBase_InterfaceSOAPSerializer.getXmlType())) {
            return myns1_BatchBase__BatchBase_InterfaceSOAPSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_BatchRequestItem__BatchRequestItem_LiteralSerializer.getXmlType())) {
            return myns1_BatchRequestItem__BatchRequestItem_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_BatchResponseItem__BatchResponseItem_LiteralSerializer.getXmlType())) {
            return myns1_BatchResponseItem__BatchResponseItem_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_BatchItemBase__BatchItemBase_InterfaceSOAPSerializer.getXmlType())) {
            return myns1_BatchItemBase__BatchItemBase_InterfaceSOAPSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_CloseGroupResponse__CloseGroupResponse_LiteralSerializer.getXmlType())) {
            return myns1_CloseGroupResponse__CloseGroupResponse_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_CloseOutResult__CloseOutResult_LiteralSerializer.getXmlType())) {
            return myns1_CloseOutResult__CloseOutResult_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_CompoundError__CompoundError_LiteralSerializer.getXmlType())) {
            return myns1_CompoundError__CompoundError_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_Package__Package_LiteralSerializer.getXmlType())) {
            return myns1_Package__Package_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_CompoundErrorBase__CompoundErrorBase_InterfaceSOAPSerializer.getXmlType())) {
            return myns1_CompoundErrorBase__CompoundErrorBase_InterfaceSOAPSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_Group__Group_LiteralSerializer.getXmlType())) {
            return myns1_Group__Group_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_Grouping__Grouping_LiteralSerializer.getXmlType())) {
            return myns1_Grouping__Grouping_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_LicenseValidationResponse__LicenseValidationResponse_LiteralSerializer.getXmlType())) {
            return myns1_LicenseValidationResponse__LicenseValidationResponse_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_ModifyPackageListResult__ModifyPackageListResult_LiteralSerializer.getXmlType())) {
            return myns1_ModifyPackageListResult__ModifyPackageListResult_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_ModifyPackageResult__ModifyPackageResult_LiteralSerializer.getXmlType())) {
            return myns1_ModifyPackageResult__ModifyPackageResult_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_PackDetail__PackDetail_LiteralSerializer.getXmlType())) {
            return myns1_PackDetail__PackDetail_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_PackDetailBase__PackDetailBase_InterfaceSOAPSerializer.getXmlType())) {
            return myns1_PackDetailBase__PackDetailBase_InterfaceSOAPSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_PackOrderLineError__PackOrderLineError_LiteralSerializer.getXmlType())) {
            return myns1_PackOrderLineError__PackOrderLineError_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_PackRateDetail__PackRateDetail_LiteralSerializer.getXmlType())) {
            return myns1_PackRateDetail__PackRateDetail_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_PackRateResponse__PackRateResponse_LiteralSerializer.getXmlType())) {
            return myns1_PackRateResponse__PackRateResponse_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_PackResponse__PackResponse_LiteralSerializer.getXmlType())) {
            return myns1_PackResponse__PackResponse_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_PackResponseBase__PackResponseBase_InterfaceSOAPSerializer.getXmlType())) {
            return myns1_PackResponseBase__PackResponseBase_InterfaceSOAPSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_PackageRequest__PackageRequest_LiteralSerializer.getXmlType())) {
            return myns1_PackageRequest__PackageRequest_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_PackageResponse__PackageResponse_LiteralSerializer.getXmlType())) {
            return myns1_PackageResponse__PackageResponse_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_ReProcessResponse__ReProcessResponse_LiteralSerializer.getXmlType())) {
            return myns1_ReProcessResponse__ReProcessResponse_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_SoxDocument__SoxDocument_LiteralSerializer.getXmlType())) {
            return myns1_SoxDocument__SoxDocument_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_SoxReturn__SoxReturn_LiteralSerializer.getXmlType())) {
            return myns1_SoxReturn__SoxReturn_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType == null || elementType.equals(myns1_ErrorBase__ErrorBase_LiteralSerializer.getXmlType())) {
            java.lang.Object obj = myns1_ErrorBase__ErrorBase_LiteralSerializer.deserialize(name, reader, context);
            return obj;
        }
        throw new DeserializationException("soap.unexpectedElementType", new java.lang.Object[] {"", elementType.toString()},DeserializationException.FAULT_CODE_CLIENT);
    }
    
    public void doSerializeInstance(java.lang.Object obj, QName name, SerializerCallback callback,
        XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ErrorBase instance = (com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ErrorBase)obj;
        
        if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.BatchRequest) {
            myns1_BatchRequest__BatchRequest_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.BatchResponse) {
            myns1_BatchResponse__BatchResponse_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.BatchBase) {
            myns1_BatchBase__BatchBase_InterfaceSOAPSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.BatchRequestItem) {
            myns1_BatchRequestItem__BatchRequestItem_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.BatchResponseItem) {
            myns1_BatchResponseItem__BatchResponseItem_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.BatchItemBase) {
            myns1_BatchItemBase__BatchItemBase_InterfaceSOAPSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CloseGroupResponse) {
            myns1_CloseGroupResponse__CloseGroupResponse_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CloseOutResult) {
            myns1_CloseOutResult__CloseOutResult_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CompoundError) {
            myns1_CompoundError__CompoundError_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Package) {
            myns1_Package__Package_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.CompoundErrorBase) {
            myns1_CompoundErrorBase__CompoundErrorBase_InterfaceSOAPSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Group) {
            myns1_Group__Group_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Grouping) {
            myns1_Grouping__Grouping_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.LicenseValidationResponse) {
            myns1_LicenseValidationResponse__LicenseValidationResponse_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ModifyPackageListResult) {
            myns1_ModifyPackageListResult__ModifyPackageListResult_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ModifyPackageResult) {
            myns1_ModifyPackageResult__ModifyPackageResult_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackDetail) {
            myns1_PackDetail__PackDetail_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackDetailBase) {
            myns1_PackDetailBase__PackDetailBase_InterfaceSOAPSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackOrderLineError) {
            myns1_PackOrderLineError__PackOrderLineError_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRateDetail) {
            myns1_PackRateDetail__PackRateDetail_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRateResponse) {
            myns1_PackRateResponse__PackRateResponse_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackResponse) {
            myns1_PackResponse__PackResponse_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackResponseBase) {
            myns1_PackResponseBase__PackResponseBase_InterfaceSOAPSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackageRequest) {
            myns1_PackageRequest__PackageRequest_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackageResponse) {
            myns1_PackageResponse__PackageResponse_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ReProcessResponse) {
            myns1_ReProcessResponse__ReProcessResponse_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxDocument) {
            myns1_SoxDocument__SoxDocument_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.SoxReturn) {
            myns1_SoxReturn__SoxReturn_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else {
            myns1_ErrorBase__ErrorBase_LiteralSerializer.serialize(obj, name, callback, writer, context);
        }
    }
}
