// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.literal.*;
import oracle.j2ee.ws.common.encoding.literal.DetailFragmentDeserializer;
import oracle.j2ee.ws.common.encoding.simpletype.*;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.SOAPEnvelopeConstants;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import oracle.j2ee.ws.common.util.xml.UUID;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.xml.soap.SOAPMessage;
import javax.xml.soap.AttachmentPart;

public class LoadBatchItemResponse_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable {
    private static final QName ns1_LoadBatchItemResult_QNAME = new QName("http://PSI.Wcf", "LoadBatchItemResult");
    private static final QName ns1_ShipmentRequest_TYPE_QNAME = new QName("http://PSI.Wcf", "ShipmentRequest");
    private CombinedSerializer myns1_ShipmentRequest__ShipmentRequest_LiteralSerializer;
    
    public LoadBatchItemResponse_LiteralSerializer(QName type) {
        this(type,  false);
    }
    
    public LoadBatchItemResponse_LiteralSerializer(QName type, boolean encodeType) {
        super(type, true, encodeType);
        setSOAPVersion(SOAPVersion.SOAP_11);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns1_ShipmentRequest__ShipmentRequest_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ShipmentRequest.class, ns1_ShipmentRequest_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.LoadBatchItemResponse instance = new com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.LoadBatchItemResponse();
        java.lang.Object member=null;
        QName elementName;
        List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        java.util.HashSet requiredElements = new java.util.HashSet();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_LoadBatchItemResult_QNAME))) {
            myns1_ShipmentRequest__ShipmentRequest_LiteralSerializer.setNullable( false );
            member = myns1_ShipmentRequest__ShipmentRequest_LiteralSerializer.deserialize(ns1_LoadBatchItemResult_QNAME, reader, context);
            requiredElements.remove("LoadBatchItemResult");
            if (member == null) {
                throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
            }
            instance.setLoadBatchItemResult((com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ShipmentRequest)member);
            context.setXmlFragmentWrapperName( null );
            reader.nextElementContent();
        }
        if (!requiredElements.isEmpty()) {
            throw new DeserializationException( "literal.expectedElementName" , requiredElements.iterator().next().toString(), DeserializationException.FAULT_CODE_CLIENT );
        }
        
        if( reader.getState() != XMLReader.END)
        {
            reader.skipElement();
        }
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.LoadBatchItemResponse instance = (com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.LoadBatchItemResponse)obj;
        
    }
    public void doSerializeAnyAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.LoadBatchItemResponse instance = (com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.LoadBatchItemResponse)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.LoadBatchItemResponse instance = (com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.LoadBatchItemResponse)obj;
        
        if (instance.getLoadBatchItemResult() != null) {
            myns1_ShipmentRequest__ShipmentRequest_LiteralSerializer.setNullable( false );
            myns1_ShipmentRequest__ShipmentRequest_LiteralSerializer.serialize(instance.getLoadBatchItemResult(), ns1_LoadBatchItemResult_QNAME, null, writer, context);
        }
    }
}
