// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.literal.DetailFragmentDeserializer;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class PackRequestBase_InterfaceSOAPSerializer extends InterfaceSerializerBase implements Initializable {
    private static final QName ns1_PackRateRequest_TYPE_QNAME = new QName("http://PSI.Wcf", "PackRateRequest");
    private CombinedSerializer myns1_PackRateRequest__PackRateRequest_LiteralSerializer;
    private static final QName ns1_PackRequest_TYPE_QNAME = new QName("http://PSI.Wcf", "PackRequest");
    private CombinedSerializer myns1_PackRequest__PackRequest_LiteralSerializer;
    private CombinedSerializer myns1_PackRequestBase__PackRequestBase_LiteralSerializer;
    
    public PackRequestBase_InterfaceSOAPSerializer(QName type, boolean encodeType, boolean isNullable, SOAPVersion soapVersion) {
        super(type, encodeType, isNullable, soapVersion);
    }
    public PackRequestBase_InterfaceSOAPSerializer(QName type, boolean encodeType) {
        super(type, encodeType, true, null);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns1_PackRateRequest__PackRateRequest_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRateRequest.class, ns1_PackRateRequest_TYPE_QNAME);
        myns1_PackRateRequest__PackRateRequest_LiteralSerializer = myns1_PackRateRequest__PackRateRequest_LiteralSerializer.getInnermostSerializer();
        myns1_PackRequest__PackRequest_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRequest.class, ns1_PackRequest_TYPE_QNAME);
        myns1_PackRequest__PackRequest_LiteralSerializer = myns1_PackRequest__PackRequest_LiteralSerializer.getInnermostSerializer();
        QName type = new QName("http://PSI.Wcf", "PackRequestBase");
        CombinedSerializer interfaceSerializer = new com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.runtime.PackRequestBase_LiteralSerializer(type, DONT_ENCODE_TYPE);
        myns1_PackRequestBase__PackRequestBase_LiteralSerializer = interfaceSerializer.getInnermostSerializer();
        if (myns1_PackRequestBase__PackRequestBase_LiteralSerializer instanceof Initializable) {
            ((Initializable)myns1_PackRequestBase__PackRequestBase_LiteralSerializer).initialize(registry);
        }
    }
    
    public java.lang.Object doDeserialize(QName name, XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        QName elementType = getType(reader);
        if (elementType != null && elementType.equals(myns1_PackRateRequest__PackRateRequest_LiteralSerializer.getXmlType())) {
            return myns1_PackRateRequest__PackRateRequest_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(myns1_PackRequest__PackRequest_LiteralSerializer.getXmlType())) {
            return myns1_PackRequest__PackRequest_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType == null || elementType.equals(myns1_PackRequestBase__PackRequestBase_LiteralSerializer.getXmlType())) {
            java.lang.Object obj = myns1_PackRequestBase__PackRequestBase_LiteralSerializer.deserialize(name, reader, context);
            return obj;
        }
        throw new DeserializationException("soap.unexpectedElementType", new java.lang.Object[] {"", elementType.toString()},DeserializationException.FAULT_CODE_CLIENT);
    }
    
    public void doSerializeInstance(java.lang.Object obj, QName name, SerializerCallback callback,
        XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRequestBase instance = (com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRequestBase)obj;
        
        if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRateRequest) {
            myns1_PackRateRequest__PackRateRequest_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRequest) {
            myns1_PackRequest__PackRequest_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else {
            myns1_PackRequestBase__PackRequestBase_LiteralSerializer.serialize(obj, name, callback, writer, context);
        }
    }
}
