// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.literal.*;
import oracle.j2ee.ws.common.encoding.literal.DetailFragmentDeserializer;
import oracle.j2ee.ws.common.encoding.simpletype.*;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.SOAPEnvelopeConstants;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import oracle.j2ee.ws.common.util.xml.UUID;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.xml.soap.SOAPMessage;
import javax.xml.soap.AttachmentPart;

public class PackRate_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable {
    private static final QName ns1_container_QNAME = new QName("http://PSI.Wcf", "container");
    private static final QName ns1_Container_TYPE_QNAME = new QName("http://PSI.Wcf", "Container");
    private CombinedSerializer myns1_Container__Container_LiteralSerializer;
    private static final QName ns1_total_weight_QNAME = new QName("http://PSI.Wcf", "total_weight");
    private static final QName ns1_Weight_TYPE_QNAME = new QName("http://PSI.Wcf", "Weight");
    private CombinedSerializer myns1_Weight__Weight_LiteralSerializer;
    private static final QName ns1_item_volume_QNAME = new QName("http://PSI.Wcf", "item_volume");
    private static final QName ns2_double_TYPE_QNAME = SchemaConstants.QNAME_TYPE_DOUBLE;
    private CombinedSerializer myns2__double__java_lang_Double_Double_Serializer;
    private static final QName ns1_cube_utilization_QNAME = new QName("http://PSI.Wcf", "cube_utilization");
    private static final QName ns1_order_lines_QNAME = new QName("http://PSI.Wcf", "order_lines");
    private static final QName ns1_ArrayOfPackOrderLine_TYPE_QNAME = new QName("http://PSI.Wcf", "ArrayOfPackOrderLine");
    private CombinedSerializer myns1_ArrayOfPackOrderLine__ArrayOfPackOrderLine_LiteralSerializer;
    private static final QName ns1_additional_information_QNAME = new QName("http://PSI.Wcf", "additional_information");
    private static final QName ns2_anyType_TYPE_QNAME = SchemaConstants.QNAME_TYPE_URTYPE;
    private CombinedSerializer ns2_anyType_TYPE_QNAMEjava$2e$lang$2e$Object_Serializer;
    private static final QName ns1_published_cost_QNAME = new QName("http://PSI.Wcf", "published_cost");
    private static final QName ns1_discounted_cost_QNAME = new QName("http://PSI.Wcf", "discounted_cost");
    private static final QName ns1_time_in_transit_days_QNAME = new QName("http://PSI.Wcf", "time_in_transit_days");
    private static final QName ns2_int_TYPE_QNAME = SchemaConstants.QNAME_TYPE_INT;
    private CombinedSerializer myns2__int__java_lang_Integer_Int_Serializer;
    private static final QName ns1_arrive_date_QNAME = new QName("http://PSI.Wcf", "arrive_date");
    private static final QName ns2_dateTime_TYPE_QNAME = SchemaConstants.QNAME_TYPE_DATE_TIME;
    private CombinedSerializer myns2_dateTime__java_util_Calendar_DateTimeCalendar_Serializer;
    
    public PackRate_LiteralSerializer(QName type) {
        this(type,  false);
    }
    
    public PackRate_LiteralSerializer(QName type, boolean encodeType) {
        super(type, true, encodeType);
        setSOAPVersion(SOAPVersion.SOAP_11);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns1_Container__Container_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Container.class, ns1_Container_TYPE_QNAME);
        myns1_Weight__Weight_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Weight.class, ns1_Weight_TYPE_QNAME);
        myns2__double__java_lang_Double_Double_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.Double.class, ns2_double_TYPE_QNAME);
        myns1_ArrayOfPackOrderLine__ArrayOfPackOrderLine_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ArrayOfPackOrderLine.class, ns1_ArrayOfPackOrderLine_TYPE_QNAME);
        ns2_anyType_TYPE_QNAMEjava$2e$lang$2e$Object_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.Object.class, ns2_anyType_TYPE_QNAME);
        myns2__int__java_lang_Integer_Int_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.Integer.class, ns2_int_TYPE_QNAME);
        myns2_dateTime__java_util_Calendar_DateTimeCalendar_Serializer = (CombinedSerializer)registry.getSerializer("", java.util.Calendar.class, ns2_dateTime_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate instance = new com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate();
        java.lang.Object member=null;
        QName elementName;
        List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        java.util.HashSet requiredElements = new java.util.HashSet();
        for (int memberIndex = 0; memberIndex <10; memberIndex++) {
            elementName = reader.getName();
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_container_QNAME))) {
                myns1_Container__Container_LiteralSerializer.setNullable( false );
                member = myns1_Container__Container_LiteralSerializer.deserialize(ns1_container_QNAME, reader, context);
                requiredElements.remove("container");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setContainer((com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Container)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_total_weight_QNAME))) {
                myns1_Weight__Weight_LiteralSerializer.setNullable( false );
                member = myns1_Weight__Weight_LiteralSerializer.deserialize(ns1_total_weight_QNAME, reader, context);
                requiredElements.remove("total_weight");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setTotal_weight((com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.Weight)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_item_volume_QNAME))) {
                myns2__double__java_lang_Double_Double_Serializer.setNullable( false );
                member = myns2__double__java_lang_Double_Double_Serializer.deserialize(ns1_item_volume_QNAME, reader, context);
                requiredElements.remove("item_volume");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setItem_volume((java.lang.Double)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_cube_utilization_QNAME))) {
                myns2__double__java_lang_Double_Double_Serializer.setNullable( false );
                member = myns2__double__java_lang_Double_Double_Serializer.deserialize(ns1_cube_utilization_QNAME, reader, context);
                requiredElements.remove("cube_utilization");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setCube_utilization((java.lang.Double)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_order_lines_QNAME))) {
                myns1_ArrayOfPackOrderLine__ArrayOfPackOrderLine_LiteralSerializer.setNullable( false );
                member = myns1_ArrayOfPackOrderLine__ArrayOfPackOrderLine_LiteralSerializer.deserialize(ns1_order_lines_QNAME, reader, context);
                requiredElements.remove("order_lines");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setOrder_lines((member == null)? null : ((com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ArrayOfPackOrderLine)member).toArray());
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_additional_information_QNAME))) {
                ns2_anyType_TYPE_QNAMEjava$2e$lang$2e$Object_Serializer.setNullable( false );
                member = ns2_anyType_TYPE_QNAMEjava$2e$lang$2e$Object_Serializer.deserialize(ns1_additional_information_QNAME, reader, context);
                requiredElements.remove("additional_information");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setAdditional_information((java.lang.Object)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_published_cost_QNAME))) {
                myns2__double__java_lang_Double_Double_Serializer.setNullable( false );
                member = myns2__double__java_lang_Double_Double_Serializer.deserialize(ns1_published_cost_QNAME, reader, context);
                requiredElements.remove("published_cost");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setPublished_cost((java.lang.Double)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_discounted_cost_QNAME))) {
                myns2__double__java_lang_Double_Double_Serializer.setNullable( false );
                member = myns2__double__java_lang_Double_Double_Serializer.deserialize(ns1_discounted_cost_QNAME, reader, context);
                requiredElements.remove("discounted_cost");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setDiscounted_cost((java.lang.Double)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_time_in_transit_days_QNAME))) {
                myns2__int__java_lang_Integer_Int_Serializer.setNullable( false );
                member = myns2__int__java_lang_Integer_Int_Serializer.deserialize(ns1_time_in_transit_days_QNAME, reader, context);
                requiredElements.remove("time_in_transit_days");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setTime_in_transit_days((java.lang.Integer)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_arrive_date_QNAME))) {
                myns2_dateTime__java_util_Calendar_DateTimeCalendar_Serializer.setNullable( false );
                member = myns2_dateTime__java_util_Calendar_DateTimeCalendar_Serializer.deserialize(ns1_arrive_date_QNAME, reader, context);
                requiredElements.remove("arrive_date");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setArrive_date((java.util.Calendar)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
        }
        if (!requiredElements.isEmpty()) {
            throw new DeserializationException( "literal.expectedElementName" , requiredElements.iterator().next().toString(), DeserializationException.FAULT_CODE_CLIENT );
        }
        
        if( reader.getState() != XMLReader.END)
        {
            reader.skipElement();
        }
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate instance = (com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate)obj;
        
    }
    public void doSerializeAnyAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate instance = (com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate instance = (com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.PackRate)obj;
        
        if (instance.getContainer() != null) {
            myns1_Container__Container_LiteralSerializer.setNullable( false );
            myns1_Container__Container_LiteralSerializer.serialize(instance.getContainer(), ns1_container_QNAME, null, writer, context);
        }
        if (instance.getTotal_weight() != null) {
            myns1_Weight__Weight_LiteralSerializer.setNullable( false );
            myns1_Weight__Weight_LiteralSerializer.serialize(instance.getTotal_weight(), ns1_total_weight_QNAME, null, writer, context);
        }
        if (instance.getItem_volume() != null) {
            myns2__double__java_lang_Double_Double_Serializer.setNullable( false );
            myns2__double__java_lang_Double_Double_Serializer.serialize(instance.getItem_volume(), ns1_item_volume_QNAME, null, writer, context);
        }
        if (instance.getCube_utilization() != null) {
            myns2__double__java_lang_Double_Double_Serializer.setNullable( false );
            myns2__double__java_lang_Double_Double_Serializer.serialize(instance.getCube_utilization(), ns1_cube_utilization_QNAME, null, writer, context);
        }
        if (instance.getOrder_lines() != null) {
            myns1_ArrayOfPackOrderLine__ArrayOfPackOrderLine_LiteralSerializer.setNullable( false );
            com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ArrayOfPackOrderLine instanceGetOrder_lines_arrayWrapper = (instance.getOrder_lines() == null) ? null : new com.aasc.erp.carrier.shipexec.proxy.types.psi.wcf.ArrayOfPackOrderLine(instance.getOrder_lines());
            myns1_ArrayOfPackOrderLine__ArrayOfPackOrderLine_LiteralSerializer.serialize(instanceGetOrder_lines_arrayWrapper, ns1_order_lines_QNAME, null, writer, context);
        }
        if (instance.getAdditional_information() != null) {
            ns2_anyType_TYPE_QNAMEjava$2e$lang$2e$Object_Serializer.setNullable( false );
            ns2_anyType_TYPE_QNAMEjava$2e$lang$2e$Object_Serializer.serialize(instance.getAdditional_information(), ns1_additional_information_QNAME, null, writer, context);
        }
        if (instance.getPublished_cost() != null) {
            myns2__double__java_lang_Double_Double_Serializer.setNullable( false );
            myns2__double__java_lang_Double_Double_Serializer.serialize(instance.getPublished_cost(), ns1_published_cost_QNAME, null, writer, context);
        }
        if (instance.getDiscounted_cost() != null) {
            myns2__double__java_lang_Double_Double_Serializer.setNullable( false );
            myns2__double__java_lang_Double_Double_Serializer.serialize(instance.getDiscounted_cost(), ns1_discounted_cost_QNAME, null, writer, context);
        }
        if (instance.getTime_in_transit_days() != null) {
            myns2__int__java_lang_Integer_Int_Serializer.setNullable( false );
            myns2__int__java_lang_Integer_Int_Serializer.serialize(instance.getTime_in_transit_days(), ns1_time_in_transit_days_QNAME, null, writer, context);
        }
        if (instance.getArrive_date() != null) {
            myns2_dateTime__java_util_Calendar_DateTimeCalendar_Serializer.setNullable( false );
            myns2_dateTime__java_util_Calendar_DateTimeCalendar_Serializer.serialize(instance.getArrive_date(), ns1_arrive_date_QNAME, null, writer, context);
        }
    }
}
